- CHANGES.txt
- docs/source/enable_basic_tools.rst
- docs/source/index.rst
- enable/testing.py
- enable/tests/tools/button_tool_test_case.py
- enable/tools/button_tool.py
- examples/enable/tools/button_tool.py
Basically a common tool that can be used whenever we want something to be "clickable" or "togglable".  Probably of significant utility in Chaco.
Has tests and documentation.
Ready for review.
> Simple Button Tool

- .travis.yml
- dev_requirements.txt
Use `pip` without dependencies to avoid Pillow install.
Hopefully fixes #170
> Fix Travis PIL Requirements

- .travis.yml
- dev_requirements.txt
- enable/__init__.py
- requirements-2.6.txt
- setup.py
This PR tries to fix the requirements for kiva and enable and at the same time clean-up the travis-ci build
> Cleanup setup and requirements

- TODO.txt
The travis-ci badge has been showing failing even thought the current master is not failing. The issue was that the travis-ci configuration for enable was only running for PRs (not merge operations). 
I have updated the travis-ci configuration and hopefully this PR will make everything right when it is merged
> Create a dummy PR to fix the problems with the travis-ci badge

- kiva/quartz/setup.py
This is required to fix `kiva.quartz` when built on os x 10.7
> BUG: fix missing framework when building kiva.quartz.

- .gitignore
This was missed when it was added in #178
> Add the auto-generated enable/_version.py to .gitignore

- CHANGES.txt
- setup.py
This PR fixes issue #197 by using enable._version.py as the file to look for version information when installing from source.
> Fix issue 197

- enable/qt4/scrollbar.py
- enable/tests/qt4/scrollbar_test.py
Scrolling was in the reverse direction for vertical scrollbars (ie. when scrollbar was at top, view was at bottom and vice-versa).  This fixes this issue.
Testing is difficult for this - have just spent an unproductive hour trying to get something working.  We probably want a little set of utility routines.  I'll leave it up to the PR reviewer as to whether we should try to add tests before merging.
> Fix scrolling problem with Qt native scrollbar

- .travis.yml
- kiva/agg/src/graphics_context.i
- kiva/compat.py
- kiva/tests/test_graphics_context.py
The new Pillow 3.0.x has the `tostring` and `fromstring` methods from `Image` raise an exception. This PR fixed enable the support for Pillow 3.0.x
in more details:
- a compatibility module is added to allow using new and old versions of Pillow
- Wx and Qt backends are checked against Pillow 3.0.0
-  The null.image backend is check against Pillow<3.0.0 and Pillow 3.0.0 on python 2.7 and only on Pillow<3.0.0 on python 2.6
> fix support for Pillow 3.0.x

- MANIFEST.in
- docs/source/conf.py
> Add docs and examples to the source distribution

- enable/qt4/scrollbar.py
- enable/scrolled.py
- enable/tests/viewport_test_case.py
- enable/viewport.py
- examples/enable/scrolled_canvas_demo.py
- examples/enable/scrolled_demo.py
This adds logic to the `Viewport` component (and some auxiliary changes for the `Scrolled` component) that allows move familiar scrolling conventions.
Viewports can now specify horizontal and vertical anchors for the view which indicate where the initial position of the viewport should be relative to the component, and the fixed point when the bounds of the view change.
In addition the unimplemented `stay_inside` option is now implemented: when changing the bounds of the viewport the view will try to stay within the bounds of the viewed component, if possible.
This PR is built on #205, since it makes the interactive testing easier, but is technically orthogonal to it.
Tests included.
> Viewport resizing

- kiva/agg/setup.py
> Don't barf if the g++ version string doesn't parse correctly

- enable/viewport.py
Fixes #228 - problem was caused by anchor traits and position/bounds getting set in "wrong" order by random dictionary hash order.  The fix simply ensures that if they are provided, the position and bounds are set after the anchor traits.
> Be deterministic about initial state of viewport position and bounds

- enable/savage/svg/backends/wx/renderer.py
wxPython 2.9+ supports a collection of gradient stops instead of just start and end.
> allow multiple gradient stops with wx toolkit

- enable/testing.py
- enable/tests/test_assistant_test_case.py
> Don't assume window is MockWindow when dealing with pointer position

- kiva/agg/src/agg_typemaps.i
- kiva/agg/src/hit_test.i
- kiva/agg/src/kiva_hit_test.cpp
- kiva/agg/src/kiva_hit_test.h
Fixes #237.
Using `unsigned char` for boolean array rather than `int`.
> Change points_in_polygon to return boolean array

- travis-ci-requirements
See https://github.com/enthought/chaco/pull/320#issuecomment-257832291 for context
> DEV: Add six to travis requirements.

- README.rst
- setup.py
Fixes #254 and #253
six was already in the `__requires__` list in enable/__init__.py.
> Don't import kiva/_version.py from setup.py

- CONTRIBUTING.rst
As discussed in #260, a contribution guide has been added to clarify policies for ongoing development.
> Add a contribution guide

- enable/savage/svg/backends/kiva/renderer.py
Fixes #267 
The `CompiledPath` class in the kiva savage backend already had a workaround for the `get_current_point` method being absent. It only needed to be connected.
> Call GetCurrentPoint as intended

- kiva/agg/src/graphics_context.i
- kiva/tests/test_macport.py
numpy 1.12 completes the deprecation of floats as shapes. The `GraphicsContext()` constructor permits such floats, so we coerce internally at the last possible moment.
This also fixes the skip logic for an unrelated test so that I'd have a clean test suite.
This should fix the test failure in enthought/chaco#342 in the one Travis environment that is using numpy 1.12.
> Ensure integer sizes

- kiva/fonttools/font_manager.py
Quick-fix for #266.  On OS X, this restores the enable-4.5.1 functionality; my Canopy Data app prints a few warnings to the terminal, and then launches normally.
> FIX: Don't crash if the list of fonts is empty

- travis-ci-requirements
It looks like fonttools is undergoing rapid change.  Fixing version form December that should be good.
> Use older version of fonttools

- CHANGES.txt
- enable/savage/svg/backends/kiva/renderer.py
- kiva/agg/src/graphics_context.i
- kiva/fonttools/font_manager.py
- kiva/tests/test_macport.py
[Note: PR is against a newly-created maint/4.6.x branch, created from the 4.6.1 release tag, with its version bumped and `IS_RELEASED` set to `False`.]
Backport commits from PRs #268, #269 and #272, in preparation for a 4.6.2 release.
> Backport bugfixes from master

- setup.py
I believe that this is the correct fix for the issue identified in #73. I've double-checked that the tarball built with `python setup.py sdist` includes the `data/button_toggle.svg` file.
> setup.py: use package_data instead of pretending that a non-package is a package

- enable/tests/test_component_editor.py
Wow... so this unit test was depending on an `import nose` in a module which it was doing an `import *` from.
This fixes some test failures seen in #279
> Don't use import * to borrow imports from other modules

- kiva/agg/__init__.py
- kiva/tests/points_in_polygon_test.py
@rkern: As requested.
I'm depending a bit on CI here to test this since I was having 2to3 problems locally (in other modules).
> Add points_in_polygon to kiva.agg with DeprecationWarning

- README.rst
It seems like it is now needed to compile enable, so this adds it together with Swig and Cython as required dependency.
> Trivial: add fonttools to dependencies in README

- enable/events.py
- enable/qt4/base_window.py
- enable/qt4/constants.py
- enable/testing.py
- enable/tests/qt4/mouse_wheel_test_case.py
- enable/tests/wx/mouse_wheel_test_case.py
- enable/toolkit_constants.py
- enable/wx/base_window.py
- enable/wx/constants.py
This PR does three things:
- makes scroll wheel rotation values on Wx floating point values.  Fixes #286. 
- adds support for horizontal mouse wheel events via a new `mouse_wheel_axis` trait on `MouseEvents`.  This fixes #134.
- adds tests of the mouse wheel logic for mouse events on Wx and Qt.
> Improve mouse wheel support

- examples/kiva_explorer.py
This didn't get converted to Python 2/3 correctly
> Fix an exec() syntax error

- examples/enable/latency_demo.py
- examples/enable/view_bounds_test.py
This just adds in `print_function` imports in a couple of examples they were missing from causing `SyntaxError`s in Python 2.
> FIX: missing print_function imports

- ci/edmtool.py
- kiva/_cython_speedups.cpp
- kiva/_cython_speedups.pyx
- kiva/tests/points_in_polygon_test.py
This is a follow up to enthought/chaco#409. Cython expects arrays which will be assigned to a memoryview to be C-contiguous. Transposed arrays are not contiguous, so now we force them to be.
> FIX: Ensure contiguous transposed arrays

- enable/testing.py
- enable/tests/test_assistant_test_case.py
- enable/tests/tools/apptools/commands_test_case.py
- enable/tests/tools/apptools/move_command_tool_test_case.py
- enable/tests/tools/apptools/resize_command_tool_test_case.py
- enable/tests/tools/apptools/undo_tool_test_case.py
- enable/tests/wx/mouse_wheel_test_case.py
- kiva/testing.py
Remove the need for the 3rd party `mock` when using Python 3 by switching to `unittest.mock`.
Closes #314
> Replace mock with unittest.mock when using Python 3

- MANIFEST.in
The license requires that the license be included in all copies of the program.  Also include some other documentation files.
> Include licenses and other files in sdists

- .travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> Remove `sudo: false` from Travis config

- enable/savage/trait_defs/ui/qt4/svg_button_editor.py
In testing Qt5 support the `enable` package throws and error when calling `QtCore.QObject.connect` directly.  Instead use `control.clicked.connect` to connect to the `clicked()` signal.
> Use correct form of signal linkage for Qt5

- enable/qt4/base_window.py
As brought up in enthought/pyface/pull/356, Enable's Qt widget should be preventing the `contextMenuEvent` via its context menu policy. Otherwise, the event will bubble up to parent containers which, not knowing that its descendant might want to handle right-click events itself, will define a context menu and interfere.
Enable does not have a separate context menu event in its `Event` API, so we don't have a need to handle them explicitly on the Qt side either. You can still use the `ContextMenuTool` if you want to add a context menu to your Enable widget. It uses the right-click mouse event.
> BUG: prevent context menus in Enable Qt widgets.

- enable/abstract_window.py
Otherwise the damaged regions list of components that have been shown at some point but are no longer visible and thus do not receive paint events can grow arbitrarily long, consuming large amounts of memory. This memory would be released if the component became visible again but who knows when/if that happens.
In our application we have TraitsUI tabs that contain Chaco plots whose PlotDatas are updated regardless of the current tab, and the plots in tabs that are not currently visible can "leak" several megabytes per minute.
I'm not familiar with the innards of Chaco/Enable, and this is just a quick solution proposal, so if you don't like this idea, feel free to bake a better one.
An example program showing the problem (I'm using pyqt backend but I don't think it matters):
1. Run for a …
> Add a maximum length to the damaged regions list to curb memory hogging

- enable/savage/svg/backends/kiva/renderer.py
- enable/savage/svg/backends/null/null_renderer.py
Fix code that tries to do either `raise NotImplemented` or `raise NotImplemented()`. Since `NotImplemented` isn't an exception type, and isn't callable, both variants actually raise `TypeError`.
> Fix raising of NotImplemented (which is not an exception)

- enable/savage/trait_defs/ui/qt4/svg_button_editor.py
The SVGButton has an orientation parameter but the visual layout in Qt backend doesn't take this into account but always uses a vertical layout.
> Fix horizontal orientation support in SVGButton's Qt backend

- kiva/agg/setup.py
- kiva/quartz/setup.py
Without this change we were seeing build failures that stated `-framework OpenGL` was an unknown compiler option.  So, the theory is, something changed about how parameters were being passed between Python versions, so "-framework OpenGL" would be parsed as to separate entries in an "argv" array for a command launch-- but now "-framework OpenGL" is being passed as  one argument.  This change makes sure `-framework` and `OpenGL` are two separate args.
> Fix macOS framework linker args

- enable/qt4/base_window.py
- enable/tests/qt4/mouse_wheel_test_case.py
* pixelDelta is not provided on all platforms (see https://doc.qt.io/qt-5/qwheelevent.html#pixelDelta), so one needs to use angleDelta or scroll events won't work. For example, on Windows or X11. Perhaps pixelDelta is just reliably available on MacOS? There are probably several ways to do this, I think the one proposed here is one of the simplest. The scaling (or lack of it) between angle and pixel deltas hasn't been thought out, but I followed the existing code in this (see also the related qt4 if branch in basewindow).
* also fix the pixelDelta argument in QWheelEvent constructor calls in the related unit test: it's an integer QPoint, not a float
* add a unit test for a wheel event without pixelDelta
> Fix support for Qt5 QWheelEvents whose pixelDelta is zero

- enable/component.py
- enable/container.py
- enable/savage/svg/document.py
- enable/scrolled.py
- enable/tools/viewport_zoom_tool.py
- kiva/agg/src/graphics_context.i
- kiva/tests/agg/image_test_case.py
- kiva/tests/test_graphics_context.py
> Fix code which triggered DeprecationWarnings

- enable/qt4/constants.py
> Add more Qt mouse button names

- enable/tests/qt4/scrollbar_test.py
- enable/tests/tools/apptools/commands_test_case.py
- enable/tests/tools/apptools/move_command_tool_test_case.py
- enable/tests/tools/apptools/resize_command_tool_test_case.py
- enable/tests/tools/apptools/undo_tool_test_case.py
- enable/tests/tools/button_tool_test_case.py
- kiva/tests/test_agg_drawing.py
- kiva/tests/test_cairo_drawing.py
- kiva/tests/test_gl_drawing.py
- kiva/tests/test_graphics_context.py
- kiva/tests/test_image.py
- kiva/tests/test_pdf_drawing.py
- kiva/tests/test_ps_drawing.py
- kiva/tests/test_qpainter_drawing.py
- kiva/tests/test_svg_drawing.py
import it from the standard library instead of importing it via `traits`.
> Update unittest import

- MANIFEST.in
> Fix typo in MANIFEST.in

- appveyor.yml
I missed this in #347 
The errors are ignored by travis and now by appveyor as well.
> CI failures on wx + python 2.7 + win are expected

- .travis.yml
Followup to #353: from experimentation on other repositories, it looks as though the `mesa-common-dev` package isn't needed.
> Travis config: remove mesa-common-dev

- docs/source/conf.py
- docs/source/enable_concepts.rst
- docs/source/enable_constraints_layout.rst
- docs/source/kiva.rst
Turn on Enthought style if available; some clean-up to look better.
Aim is to be included before next release so style can be consistent with other projects.
> Quick and Dirty Documentation Improvements

- kiva/celiagg.py
Component borders were a bit fuzzy when drawn with celiagg thanks to a very specific optimization which was made in the kiva agg backend.
This replicates that in the celiagg backend as well.
> Fix rect drawing with celiagg

- docs/source/conf.py
The `html_logo` and `html_favicon` paths should be [relative to the configuration directory](http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_logo). A Sphinx build (without the enthought-sphinx-theme) currently produces:
```
copying static files... WARNING: logo file 'e-logo-rev.png' does not exist
WARNING: favicon file 'et.ico' does not exist
done
```
> Fix paths to static files.

- ci/edmtool.py
Nose was capturing logs when running the test suite, which is why we werent seeing the kiva font manager related logs/tracebacks on the enable test runs but we were seeing them in other package test runs!
(I checked the following packages and they make sure that nose doesnt capture logs - traits, traitsui, pyface. chaco doesn't use nose anymore.)
> Nose captures logs!

- kiva/fonttools/font.py
Deferring these imports means that a number of places where we need to import from `font` don't trigger the import time side-effect in the `font_manager` module.
This PR doesn't attempt to actually fix either of the issues #362 or #363 .
> Defer imports from font_manager in font module

- kiva/ps.py
`kiva.ps` was messing with the logging configuration in a pretty serious way. Then to add insult to injury, the logger instance is _never used_ anywhere in the module.
> Don't touch logging configuration

- .travis.yml
- appveyor.yml
- ci/edmtool.py
> Turn off Python27 tests

- kiva/fonttools/font_manager.py
As of fonttools 4.1, we can use `TTCollection` as a context manager directly, but we are currently using 3.29 with EDM. However, we can pass an open file object directly into `TTCollection` rather than the file path.
Also includes a tiny refactor to remove duplicated logging error message strings. 
Closes #377
> Pass file object into TTCollection and close when done

- enable/savage/trait_defs/ui/qt4/svg_editor.py
- examples/kiva_explorer.py
This PR fixes a couple of small issues found when working with the examples:
- the savage static demo didn't work on Python 3 because the XML writer expected bytes, not str.
- error reporting was broken in the KivaExplorer, and the timing editor was an editable field.
This fixes both issues.
> Small fixes for Examples

- .travis.yml
- appveyor.yml
- ci/edmtool.py
- ci/requirements.txt
- enable/tests/container_test_case.py
- enable/tests/tools/hover_tool_test_case.py
This PR's goal is to make CI green again.
Closes #423
Closes #410
I tried my best to limit the scope of this PR, but it was difficult to achieve 😂 .
In summary:
- EDM version is upgraded to use RH7 repository.
- The test failure in #423 is fixed. The test was failing in the first place but the test was not run on CI before.
- Revert half of #386 which caused CI to be run against a released egg of enable instead of local source
- Fix test errors complaining about GuiTestAssistant not being implemented on null toolkit (see this [comment](https://github.com/enthought/enable/pull/405#issuecomment-642715980)).
- Pin dependencies on traits, traitsui, pyface, apptools to released versions.
- Install traits, traitsui, pyface and apptools from EDM, remove Python 3.5 from the CI matrix. (<-- this …
> Make CI green again and remove Python 3.5 from CI

- ci/edmtool.py
fixes #429 
This PR simply bumps the runtime option default from 3.5 to 3.6 as 3.6 is what is listed in `supported_combinations`
> make python 3.6 defualt runtime for click options instead of 3.5

- .travis.yml
- ci/edmtool.py
fixes #407 
This PR makes it so that cron jobs install `pyface`, `traitsui`, and `traits` from source by adding a `--source` click option used in the install function in `edmtool.py`.
This follows what is done in other ets projects (e.g https://github.com/enthought/envisage/blob/8245931f7e3dfcb6513bfb7dc2ae9b10ca6f89a1/etstool.py#L255-L273)
Note that based on the comment
```
"traitsui==7.0.1-1",
```
and the issue #425 I expect that CI will currently fail for these cron jobs, but that is what we want so that these kinds of issues can be detected early.
> Add source click option used on cron jobs to install pyface, traitsui, and traits from source

- .travis.yml
- ci/edmtool.py
This PR simply re-adds 'wx' to `supported_combinations` in edmtool.py.  Currently we still have a CI for wx and it is an allowed failure.  However, because wx is not in this list of supported_combinations, the CI just fails immediately with 
```
RuntimeError: Python 3.6, toolkit wx, and pillow pillow not supported by test environments
Command exited with code 1
```
without actually running any tests.  Even if they fail currently it is good for the tests to be exercised with CI to see if new failures are ever introduced.
Also, this PR lifts the installation pattern for wxPython 4 from pyface as it is not yet available in EDM.
> re-adding wx as a supported combination in edmtool 

- .travis.yml
- ci/edmtool.py
fixes #431 
This PR simply installs pyqt5 from edm instead of pip.
> Use PyQt5 from EDM instead of PyPI 

- enable/testing.py
- enable/tests/test_assistant_test_case.py
- Adds `dclick` option to `EnableTestAssistant.mouse_down`
- Fixes import failure in associated test module
- Adds tests for `EnableTestAssistant.mouse_down`
Closes #438
> Add dclick option to test assistant

- ci/edmtool.py
- enable/tests/_testing.py
- enable/tests/qt4/mouse_wheel_test_case.py
- enable/tests/qt4/scrollbar_test.py
- enable/tests/test_assistant_test_case.py
- enable/tests/test_component_editor.py
- enable/tests/tools/hover_tool_test_case.py
- enable/tests/wx/mouse_wheel_test_case.py
- kiva/tests/_testing.py
- kiva/tests/test_quartz.py
Fixes #425
This PR reimplemented a few trivial test utility functions to be used within Enable and Kiva such that tests no longer import from private modules of TraitsUI. See also #443 on to what extent enable/kiva should depend on Pyface/TraitsUI. Dependency is a worse enemy to repeating oneself. The test utilities are so simple that reimplementing them is a cheap cost to enable looser coupling among the packages.
> Fix test failures when run against TraitsUI 7.1.0

- ci/edmtool.py
Closes #447
This is band-aid to the complicated setup we have so that the cron job on Travis can still run. This will be refreshed again when we move to GitHub Actions, as we are making the move in other ETS projects as well.
> Fix missing new dependencies in cron job

- enable/savage/svg/backends/wx/renderer.py
- enable/savage/trait_defs/ui/wx/svg_button_editor.py
- enable/savage/trait_defs/ui/wx/wx_render_panel.py
- enable/trait_defs/ui/wx/rgba_color_editor.py
- enable/wx/base_window.py
- enable/wx/constants.py
- kiva/trait_defs/ui/wx/kiva_font_editor.py
**NOTE:** This was pulled in from #401 to make review a bit easier.
Resolves #399
* Made `wx.VERSION` comparison more robust
* Made the test examples run on windows and using wx:
* Replaced deprecated `wx.EVT_XXX(panel, handler)` with `panel.Bind(wx.EVT_XXX, handler)` in  `rgba_color_editor.py`
* Replaced faulty `slider.SetTickFreq( 10, 1 )` with `slider.SetTickFreq(10)` in `rgba_color_editor.py`
* Fixed the failing `ToolkitEditorFactory.all_facenames` method in `kiva_font_editor.py`
* Replaced deprecated `wx.PyPanel` with `wx.Panel`
* Changed `from enable.wx_backend import Window` to `from enable.api import Window` and moved all imports to the top of the file.
* Replaced call to `wx.SystemSettings_GetMetric` with `wx.SystemSettings.GetMetric`
* Replaced call to deprecated `wx.EVT_XXXX( …
> WxPython 4 Fixes

- enable/tools/drag_tool.py
- Adds additional explanatory comments to DragTool flags
- Changes default value of `end_drag_on_leave` to False because the default value of True doesn't produce the described behavior
Closes #451
> Expand drag tool comments

- ci/edmtool.py
This PR makes the following improvements to edmtool
- ensure that `-h` works along with `--help`
- add a new `shell` command
> Make improvements to edmtool

- .travis.yml
- enable/tests/tools/hover_tool_test_case.py
- enable/tests/wx/mouse_wheel_test_case.py
- enable/wx/base_window.py
This PR fixes the few test errors for the wx test suite and change the CI configuration such that wx is required to pass.
I did not _fix_ #458, I merely turned the assertion into an "expected failure" (but without using unittest's expectedFailure, which allows unexpected errors to pass and should not be used on anything that might last for any prolonged period of time).
> Require wx CI job to pass

- docs/source/conf.py
- enable/savage/compliance/sike.py
- enable/savage/compliance/xml_view.py
part of #415 
Python 3 reads source code in UTF-8 by default, so these can all be removed
> remove all "coding: UTF-8" headers

- enable/pyglet_backend/window.py
- enable/savage/compliance/viewer.py
- enable/savage/svg/document.py
- enable/stacked_layout.py
- enable/vtk_backend/vtk_window.py
- kiva/agg/tests/compiled_path_test_case.py
- kiva/agg/tests/graphics_context_test_case.py
- kiva/cairo.py
- kiva/pdfmetrics.py
- kiva/tests/affine_test_case.py
- kiva/tests/agg/test_image3.py
This PR simply removes a bunch of commented out code from the code base.  There is certainly more that should be removed still floating around
> Remove commented out code

- ci/edmtool.py
- enable/testing.py
- enable/tests/test_assistant_test_case.py
- enable/tests/tools/apptools/commands_test_case.py
- enable/tests/tools/apptools/move_command_tool_test_case.py
- enable/tests/tools/apptools/resize_command_tool_test_case.py
- enable/tests/tools/apptools/undo_tool_test_case.py
- enable/tests/tools/hover_tool_test_case.py
- enable/tests/wx/mouse_wheel_test_case.py
- kiva/fonttools/tests/test_font_manager.py
- kiva/testing.py
part of #415 
`unittest.mock` became part of the standard library in python 3.3.  Since we are dropping all python versions <3.6 we no longer need to have `try ... except`s for these imports 
Also, as a result of this, `mock` can be removed from the list of dependencies in edmtool.py.
> Remove try excepts for importing unittest.mock

- ci/edmtool.py
- enable/tests/primitives/test_image.py
- kiva/fonttools/font.py
part of #415 
This PR removes any explicit python version checks and only keeps the code paths that are specific to python versions we plan to continue to support (python >=3.6).
> Remove python version checks 

- examples/kiva/compiled_path.py
- examples/kiva/dash.py
- examples/kiva/ellipse.py
- examples/kiva/gradient.py
- examples/kiva/rect.py
- examples/kiva/simple.py
- examples/kiva/simple2.py
- examples/kiva/star.py
- examples/kiva/star1.py
fixes #398 
This PR replaces all uses of `tempfile.mktemp` as it is deprecated and unsafe.
> Replace use of tempfile.mktemp with tempfile.NamedTemporaryFile 

- enable/savage/svg/backends/kiva/renderer.py
- enable/savage/svg/backends/kiva/tests/test_renderer.py
fixes #395 
This PR adds some tests to illustrate the dangers associated with having `[]` as a default.  It also replaces the default values of `[]` with `None`, and then explicitly checks if the value is `None` and updates the value to `[]` in the method body to avoid the danger.  
Also, I noticed some more commented out code in the file so I removed it here even though it is orthogonal to the purpose of this PR.
> Replace dangerous [] defaults with None, and explicitly check for None

- kiva/abstract_graphics_context.py
fixes #393 
This PR simply adds self as the first argument to the `draw_image` abstract method.  
I believe this was previously inconsequential because this method is always intended to be overridden.  Those overriding it  add the self argument. Apparently `@abstractmethod` doesn't strictly enforce the signature of the method, so subclasses / registered classes are free to change the signature.
In any case, this method should still take `self` as its first argument.
> Add self as the first argument to method

- README.rst
fixes #427 
This PR simply removes version number specifics from the installation requirements on the readme.  
it also removes `six` entirely as #464 has been merged
> Remove install requirement version numbers from README

- ci/edmtool.py
fixes #434 
This PR makes the exact same fix that was done in https://github.com/enthought/envisage/pull/326 and https://github.com/enthought/traitsui/pull/1059. It adds the adds the -W default flag.
> TST: Switch on default warning flag for CI test command

- docs/source/credits.rst
- docs/source/index.rst
- docs/source/kiva.rst
Per requirement of FreeType License, kiva's documentation must explicitly cite the  FreeType project. This PR adds the require clause. See https://github.com/enthought/enable/blob/76683223b1d76d94b8557d41ea266c823153fa37/kiva/agg/freetype2/docs/LICENSE.TXT and https://github.com/enthought/enable/blob/76683223b1d76d94b8557d41ea266c823153fa37/kiva/agg/freetype2/docs/FTL.TXT
> Add disclaimer in compliance with FreeType License

- docs/source/conf.py
When I tried to build the documentation with the following commands:
```
pip install sphinx
cd docs
make html
```
I get the following error:
```
Traceback (most recent call last):
File "/Users/kchoi/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/sphinx/config.py", line 319, in eval_config_file
execfile_(filename, namespace)
File "/Users/kchoi/.edm/envs/enable-test-3.6-null-pillow/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 89, in execfile_
exec(code, _globals)
File "/Users/kchoi/Work/ETS/enable/docs/source/conf.py", line 42, in <module>
execfile(os.path.join('..', '..', 'enable', '_version.py'), d)
NameError: name 'execfile' is not defined
```
`execfile` is a Python 2 built-in. This PR fixes the config file so that the config file works on Python 3. We …
> Fix documentation build failing on Python 3

- enable/savage/svg/document.py
- examples/kiva/agg/benchmark.py
- examples/kiva/agg/dash.py
- examples/kiva/agg/lion.py
- examples/kiva/agg/polygon_hit_test.py
- examples/kiva/agg/simple_clip.py
- examples/kiva/agg/text_ex.py
- examples/kiva/dash.py
- examples/kiva/simple_clip.py
closes #415 
This PR removes a couple import try excepts that were python 2 specific (e.g. `time.perf_counter` is always available since python 3.3 so we no longer need the except clause)
> Drop python2 specific imports

- kiva/fonttools/tests/test_font_manager.py
Currently running the tests for font managers causes two log messages to be emitted to console (using last resort log handler):
```
$ python -m unittest kiva.fonttools.tests.test_font_manager
/Users/kchoi/Work/ETS/py39-venv/enable-env/lib/python3.9/site-packages/fontTools/misc/py23.py:11: DeprecationWarning: The py23 module has been deprecated and will be removed in the next release. Please update your code.
warnings.warn(
.Could not open font file /Users/kchoi/Work/ETS/enable/kiva/fonttools/tests/data/TestTTC.ttc
Traceback (most recent call last):
File "/Users/kchoi/Work/ETS/enable/kiva/fonttools/font_manager.py", line 721, in createFontList
collection = TTCollection(f)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/mock.py", line 1093, in __call__
return …
```
> Maint: Make tests for font manager quieter

- .travis.yml
- appveyor.yml
- ci/.edm.yaml
- ci/edmtool.py
Currently CI builds are failing because the default config created by EDM includes a repository to `enthought/commercial` that has been ~deprecated~ (edited: removed). The default config should be fixed in EDM. In the meantime, this PR attempts to workaround the issue by specifying a config file to use.
(Orthogonal: Presumably enable should always provide a config file in all the steps involving EDM... but at the same time, if we had always provided a config, it would be harder for such issue to reveal themselves.)
> Use config for bootstrapping a EDM environment

- enable/savage/compliance/viewer.py
- enable/savage/svg/document.py
- kiva/tests/test_svg_drawing.py
Closes #490
The first commit fixes errors that can be seen by running the test suite on Python 3.9.
The second commit makes similar changes, but those changes are not covered by tests.
On the changes that are not covered by test:
For `enable.svg.document.addRectToDocument`. I was trying to write a test that does something like this:
```
def test_add_rect_to_document_with_clip_path(self):
svg_text = create_svg_text(
'<rect x="11" y="11" clip-path="circle() view-box" />'
)
document = document.SVGDocument(etree.parse(StringIO(svg_text)).getroot(), renderer=KivaRenderer())
```
However it still does not reach the code path where I fixed the usage of ElementTree.
It seems that [`if 'clip-path' in node:`](https://github.com/enthought/enable/blob/6b41a429f5cfddc70fa67c3a1025cdd426a98988/enable/sav …
> Fix AttributeError on Python 3.9 due to usage of removed API in xml

- kiva/fonttools/font.py
- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/test_font.py
- kiva/fonttools/tests/test_font_manager.py
- kiva/trait_defs/ui/wx/kiva_font_editor.py
- kiva/trait_defs/ui/wx/tests/test_kiva_font_editor.py
Closes #362
This PR removes the import side effect of building font cache in the `font_manager` module. The action of loading fonts and building the cache is deferred until the global font manager singleton is requested.  All code external to `font_manager` should use the `default_font_manager` callable to access this font manager singleton.
Benefits of this change:
- Make it harder to resurrect the import side-effect in other modules that depend on font_manager (it is too easy to introduce an import and not noticing that brings about additional side effects.)
- Make it easier to test `font_manager` without the import side effect. (The global singleton still makes testing harder.)
It might be easier to review this PR by commits. As an overview:
- Add the `default_font_manager` function …
> Remove import side effect of creating font cache in font_manager

- kiva/fonttools/font_manager.py
The USE_FONTCONFIG is a module level constant to be flipped to change the behaviour of `kiva.fonttools.font_manager` at import time. It is hard to see how this can be used apart from running the file as a script.
This PR removes code that is never run due to the fact that `USE_FONTCONFIG` is false.
> Remove USE_FONTCONFIG in font_manager

- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/test_font_manager.py
Closes #497
The module level `kiva.fonttools.font_manager.findfont` function is believed to be unused.
Note that the functionality of `FontManager.findfont` is used via the `Font.findfont` method, where `Font` is a public facing API. That functionality has been tested in `kiva.fonttools.tests.test_font`.
> Remove module level findfont in font_manager

- enable/examples/demo/enable/shapes/run.py
- enable/examples/demo/enable/tools/button_tool.py
- enable/examples/demo/enable/tools/drop_tool.py
closes #500
In this PR a few examples are update to overwrite the `_create_component` method of `DemoFrame` rather than overwriting `_create_window` (which is only used for the `pyglet` toolkit).  The logic previously contained in the `_create_window` methods could easily be pulled into the `create_component` method.  If `pyglet` is used, the actual window creation is handled by the default behavior of `_create_window` so long as `_create_component` is defined.  In non `pyglet` cases configure_traits is called and the `DemoFrame` class sets things up appropriately.
> Overwrite _create_component instead of _create_window to avoid Error in examples

- kiva/examples/kiva/kiva_explorer.py
fixes #509 
This is very short PR which simply changes `kiva_explorer` to come up as a popup rather than trying to compress it into the demo tab of the etsdemo application.  All this requires is a change to use the magic named `popup`
> Make kiva_explorer a popup

- enable/examples/demo/enable/shapes/api.py
- enable/examples/demo/enable/shapes/run.py
- enable/examples/demo/enable/tools/pyface/context_menu.py
This PR cleans up a couple demos by using absolute imports, using magically named `Demo`, and over writing `_create_component` instead of `_create_window` so that these demos can be run / run smoothly through the etsdemo application
> Clean-up a couple demos

- .travis.yml
- appveyor-run.cmd
- ci/edmtool.py
- ci/requirements.txt
This:
- installs requirements from EDM where possible,
- removes the option to use older versions of Pillow,
- installs the most recent Pyglet from PyPI
> Update CI requirements

- MANIFEST.in
The `TODO.txt` file doesnt exist anymore. It was removed in #474 so we can remove it from the manifest file.
> Remove TODO.txt from the manifest file

- setup.py
Now that we don't have any Python 2 code, we can simply remove the `use_2to3` boolean flag in setup. Note that we werent using 2to3 in the recent release anyway.
> Unset 2to3 flag from setup file

- enable/api.py
- kiva/api.py
This PR adds module docstrings to `enable.api` and `kiva.api`, in an effort to improve the api documentation of kiva and enable.
> Add module docstrings to kiva and enable api modules

- ci/edmtool.py
This PR adds `enable.null` submodule to the list of submodules that are ignored when generating the api documentation. FTR, the other modules ignored are `enable/qt4`, `enable/wx` and `*/tests`.
> Dont document null submodule in api docs

- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/_testing.py
- kiva/fonttools/tests/test_font.py
- kiva/fonttools/tests/test_font_manager.py
This PR fixes an AttributeError observed in #392. The error is caused by #488 where the import side effect of creating a module level global font manager cache is removed. There still exists usage of the global font manager assuming it had been created.
The first commit adds a test that would fail. The commit f665e53283aefeebc4299d5503933ed450e5c187 fixes the issue (it is by @jwiggins, cherry-picked from #392).
~Marking as draft to get CI run on the first commit in order to verify the test does fail (though I verified locally, I don't trust my setup when the subject is a module level cache), and then I will push the commit that fixes it.~ (Edited: Done)
> Fix Font.findfontname AttributeError when the default font manager has not been initialized

- kiva/ps.py
- kiva/svg.py
- kiva/tests/test_gl_drawing.py
Saving the graphics context to the PS and SVG backends raises resource warnings because the file handler is not closed by the save method. This PR fixes the issue by using open as a context manager.
For example, the resource warnings look like this on master - 
```
test_circle (test_ps_drawing.TestPSDrawing) ... ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Users\\rporuri\\AppData\\Local\\Temp\\tmp5jjp1zn9\\rendered.eps' mode='w' encoding='cp1252'> [test_ps_drawing.py:17]
ok
test_circle_clip (test_ps_drawing.TestPSDrawing) ... ResourceWarning: unclosed file <_io.TextIOWrapper name='C:\\Users\\rporuri\\AppData\\Local\\Temp\\tmpd9y5my5y\\rendered.eps' mode='w' encoding='cp1252'> [test_ps_drawing.py:17]
ok
test_circle_fill (test_ps_drawing.TestPSDrawing) ... ResourceWarning: …
```
> Address resource warnings because of open file handles

- .gitignore
- ci/edmtool.py
- docs/source/api/enable.api.rst
- docs/source/api/kiva.api.rst
- docs/source/api/templates/module.rst_t
- docs/source/api/templates/package.rst_t
The work in this PR has been adapted from a similar PR in traits-futures - https://github.com/enthought/traits-futures/pull/181/
In my personal opinion, this makes the api docs cleaner and less cluttered.
| before | after |
|---------|------|
|![kiva-before](https://user-images.githubusercontent.com/1926457/103408082-f7b56e80-4b58-11eb-8931-705bebba47af.png)|![kiva-after](https://user-images.githubusercontent.com/1926457/103408087-fb48f580-4b58-11eb-877b-ffb752a86970.png)|
|![enable-before](https://user-images.githubusercontent.com/1926457/103408090-013ed680-4b59-11eb-9913-aa90e31a96d4.png)|![enable-after](https://user-images.githubusercontent.com/1926457/103408094-04d25d80-4b59-11eb-949b-9f37e255746c.png)|
> Use templates when generating apidocs for enable and kiva

- .github/workflows/test-with-edm.yml
Closes #537
Certain components (e.g. kiva) are OSX specific and it would be convenient to developers if the tests are run by CI in an OSX environment, otherwise we rely on developers having an OSX host machine and remembering to run test suite locally.
Background: Other ETS projects are in the middle of moving CI to GitHub Actions (see Traits, TraitsUI, and Traits-Futures).
I also have separate [branch](https://github.com/enthought/enable/compare/ci-github-actions) where I included all the jobs we currently have in Travis/Appveyor. I decided that might be too much to review in one go. The OSX job is trivial enough so it would be more efficient to break this out. Once this gets merged, it can immediately benefit pending PRs such as #392 and #535 which have OSX specific changes.
I am happy …
> Add OSX job to CI using GitHub Actions

- .github/workflows/test-with-edm.yml
- enable/tests/test_component_editor.py
This is another incremental step towards moving what we currently have on Travis/Appveyor to GitHub Actions.
This PR adds Windows to the existing CI matrix.
One test being modified fails when we switch to the Windows worker from GitHub Actions. The test is trying to make sure that the `ComponentEditor.width` and `ComponentEditor.height` are taken into account for setting the component view size, but the upper bound in the test is only an approximation, because the window can be a bit larger due to borders and native screen size.
The test failure looks like this:
```
======================================================================
FAIL: test_initial_component_with_item_size (enable.tests.test_component_editor.TestComponentEditor) …
```
> Add Windows to the GitHub Actions CI test matrix

- kiva/tests/test_gl_drawing.py
The `TestGLDrawing` was meant to be skipped on Windows when Appveyor CI was put up (see #347), but the skip condition skips OSX as well, because the `sys.platform` for OSX is `"darwin"`, and matches `"win" in sys.platform`.
I believe one of the tests is actually failing on master + OSX, and may have been like that for a long time but CI has not tested against OSX until recently.
The first commit will relax the skip to reveal the error, and then depending on how easy it is to fix, I may just skip that one test and open an issue referencing this PR. (edited: I went for the latter)
This is motivated by #392 which also fixed the skip condition but subsequently skipping the test case again for other reasons. The second skip may mask the existing failure, and make tracking on that existing …
> Unskip most of TestGLDrawing tests on OSX

- .github/workflows/bleeding-edge.yml
- enable/__init__.py
This PR adds a cron job to the GitHub Actions workflow.
Different from the cron job currently setup on Travis which uses EDM, this cron job is setup to install everything from `pip`. 
This exercise also helps flush out missing dependency declaration in `setup.py`, which isn't used by `ci/edmtool.py`. With that, the `extras_require` declarations for optional dependencies is expanded here so that CI setup can call `pip install .[flag,...]`.  This will further benefit package distributors who will be looking for these declarations when they build enable.
As the names of the optional dependencies are tied to the cron job setup, I keep these two changes in the same PR.
Since tests on optional features are skipped if the optional dependency is absent (apart from the ones on SVG, see #543), I …
> Add cron job to GitHub Actions and expand extras_require

- enable/__init__.py
Closes #545
`pkg_resources` is used in tests. One will get import error if `setuptools` is absent (hard to replicate in CI because `setuptool` often exists). Strictly speaking, one cannot assume a Python environment must have `setuptools`.
> Declare setuptools as a test dependency

- .github/workflows/test-with-edm.yml
This PR adds the null GUI toolkit to the test matrix. This will catch most omissions to declare GUI dependencies in tests (e.g. tests with `skip_if_null` decorator).
Note that CI setup on Appveyor Windows does tests against null backend and I have not added it here.
I am wondering if it is enough to test null backend on one platform only (motivated by a desire to conserve free resources shared among OSS community).  If this is good enough, I think we have all the pieces from Travis/Appveyor ported to GitHub Actions after this PR.  If not, it is also easy for me to extend the matrix for Windows to include the null backend.
> Add null to the list of toolkits tested on GitHub Actions

- README.rst
From the exercise of setting up CI, it is evident that `libglu1-mesa-dev` is a build dependency on Linux, `pip install ` fails with lots of compilation errors if the package is absent.
This PR adds the required `libglu1-mesa-dev` (as is named on Ubuntu) on the README. The package name may vary slightly from linux distribution to distribution, though.
> Mention in the README libglu1-mesa-dev is a build dependency on Linux

- tox.ini
We're not ready to run flake8 on the code regularly yet, but with #557 and #558 in place we can now work towards that goal. To that end, I'm introducing a `tox.ini` config which adds ignores for machine generated and vendored files that we don't care to see linter errors for.
> Add tox.ini for flake8 control

- enable/savage/compliance/comparator.py
- enable/savage/compliance/sike.py
- enable/savage/compliance/xml_view.py
This PR fixes a weird usage of the traitsui api module where `traitsui.api` was being imported as `tui` - and users were then doing
`tui.View` or `tui.Group `- instead of simply importing `Group` from `traitsui.api`.
> Update traitsui.api imports

- enable/__init__.py
This PR lists `pillow` as a dependency unconditionally instead of conditionally adding it to the list of required packages depending on whether or not `PIL` can be imported.
> Unconditionally list pillow as a runtime dependency

- enable/drawing/api.py
- enable/layout/api.py
- enable/primitives/api.py
- enable/tools/api.py
- enable/tools/pyface/api.py
- enable/trait_defs/api.py
This PR adds module docstrings to the api modules in enable - which improves the readability of the published API documentation.
> Add module docstrings to api modules in enable

- setup.py
On the main branch, the `_version.py` files don't get generated in `enable` and `kiva` - because of the path provided to `write_version_py` function. The changes made here enable the generation of the version file - which also fixes an issue where documentation build is broken on windows because of the lack of the version file.
This is the right fix for the problem I was trying to solve in #519 .
> Provide the right path to the version file on windows

- enable/controls.py
- enable/enable_traits.py
- enable/primitives/annotater.py
Closes #433.
There's still a deprecation warning about using `TraitMap`, but this is coming from traits internal code, so I'm not sure anything can be done within enable.
```
/Users/jwiggins/.edm/envs/enable-test-3.6-pyqt5/lib/python3.6/site-packages/traits/traits.py:330: DeprecationWarning: 'TraitMap' trait handler has been deprecated. Use Map instead.
other.append(TraitMap(map))
```
> Stop using deprecated trait handlers

- kiva/pdf.py
- kiva/ps.py
- kiva/svg.py
- kiva/tests/drawing_tester.py
- kiva/tests/test_gl_drawing.py
- kiva/tests/test_pdf_drawing.py
- kiva/tests/test_ps_drawing.py
- kiva/tests/test_qpainter_drawing.py
**NOTE**: I expect this to fail until #569 is merged. This is due to broken implementations of `draw_image` in the PS and SVG backends.
```
======================================================================
ERROR: test_image (kiva.tests.test_ps_drawing.TestPSDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/runner/.edm/envs/enable-test-3.6-null/lib/python3.6/site-packages/kiva/tests/drawing_tester.py", line 33, in test_image
self.gc.draw_image(img, (100, 100, 20, 20))
File "/home/runner/.edm/envs/enable-test-3.6-null/lib/python3.6/site-packages/kiva/basecore2d.py", line 856, in draw_image
self.device_draw_image(img, rect)
File "/home/runner/.edm/envs/enable-test-3.6-null/lib/python3.6/site-packages/kiva/ps.py" …
```
> Add a unit test for drawing images

- README.rst
This was missed in #549
[preview of the README](https://github.com/enthought/enable/tree/cleanup/travis-badge)
> Update CI status badge

- enable/primitives/image.py
- enable/tests/primitives/test_image.py
@corranwebster: You are the author of the `Image` component. Do you recall what your motivation was for putting the image data into a `GraphicsContext` and passing that when drawing? Why not just draw directly from an array?
I'd like to phase out certain usage of AGG so that it can be removed. This is one of the spots that needs attention.
> Don't use a GraphicsContext for storage in the Image component

- enable/null/toolkit.py
- enable/qt4/toolkit.py
- enable/toolkit.py
- enable/wx/toolkit.py
- setup.py
Closes #439
I _think_ this should work, but I'm not entirely sure if it's the right approach. It makes enable directly dependent on `pyface`, which I think we're OK with now, but if that's not OK then it can be rewritten.
@corranwebster I'm really curious what your opinion is on this.
> Pyface-style toolkit selection

- CHANGES.txt
This PR updates the changelog in prep for the upcoming 5.0.0 release. ~Note that there are two PRs that are yet to be merged - which are release blockers for the 5.0.0 release - which have not been included in this changelog.~ Changelog entries for #251 and #571 are now included in this PR. This can now be merged.
> Update changelog for 5.0.0 release

- setup.py
This PR simply bumps the version number in `setup.py` for continued development in advance of the 5.0.0 release.
> Bump version for continued development (5.1.x)

- kiva/quartz/__init__.py
I removed this import in error as part of #558. It's needed by the Qt Quartz backend (`enable.qt4.quartz`).
@rahulporuri, @aaronayres35: This should be cherry-picked into the 5.0.0 branch.
> Undo removal of get_mac_context import

- enable/colors.py
- enable/component_editor.py
- enable/tools/hover_tool.py
- enable/trait_defs/rgba_color_trait.py
- enable/trait_defs/ui/rgba_color_editor.py
- kiva/trait_defs/kiva_font_trait.py
Missed this in #571. The majority of the Qt toolkit conditionals were checking `ETSConfig.toolkit == "qt4"`. This PR switches to `ETSConfig.toolkit.startswith("qt")` instead.
@rahulporuri, @aaronayres35: This should be cherry-picked into the 5.0.0 branch.
> Handle ETSConfig.toolkit == 'qt'

- kiva/examples/kiva/image_explorer.py
This is just a tiny demo which can be used to exercise the `draw_image` methods of various kiva backends. The next PR will introduce PIL `Image` support across all kiva backends and a fix for #574.
> Add an Image Explorer demo

- enable/abstract_window.py
- enable/component.py
- enable/component_editor.py
- enable/qt4/base_window.py
- enable/qt4/cairo.py
- enable/qt4/celiagg.py
- enable/qt4/gl.py
- enable/qt4/image.py
- enable/qt4/qpainter.py
- kiva/agg/__init__.py
- kiva/agg/src/graphics_context.i
- kiva/cairo.py
- kiva/celiagg.py
- kiva/gl/__init__.py
- kiva/qpainter.py
- kiva/tests/drawing_tester.py
- kiva/tests/test_agg_drawing.py
- kiva/tests/test_cairo_drawing.py
- kiva/tests/test_gl_drawing.py
- kiva/tests/test_qpainter_drawing.py
This is the Qt half of #412 and #517. I haven't looked into how Wx does HiDPI display yet, but figuring out how to do it for Qt5 first will likely make adding Wx "easy".
Known broken:
* ~`Component.use_backbuffer` creates a low resolution buffer.~
* OpenGL clipping is a bit off
* ~`GraphicsContext.clip_to_rect` uses absolute coordinates, so supporting HiDPI by changing the scale of a GC will break lots of code [but not all] which uses `clip_to_rect`~ `GraphicsContext.clip_to_rect` is not uniformly implemented with respect to the affine transformation across all kiva backends! (#592)
* ~`GraphicsContext.draw_marker_at_points` in the `kiva.agg` backend will draw nothing if there's anything more than a translation applied to the transformation matrix.~ Covered by #594
> Add HiDPI support for the Qt toolkit

- kiva/agg/src/kiva_graphics_context.h
This will be need to keep Chaco's colormapped scatterplot renderer working if #591 is merged.
> Allow scaling in agg's draw_marker_at_points

- ci/edmtool.py
- kiva/celiagg.py
- kiva/tests/test_celiagg_drawing.py
As part of the exploration for #591, I discovered that `clip_to_rect` should respect the current transformation and the celiagg backend was not doing this.
Fixes #304 (as a side effect of adding unit tests for celiagg)
> Celiagg's clip_to_rect() should respect the transform matrix

- kiva/cairo.py
- kiva/celiagg.py
- kiva/examples/kiva/image_explorer.py
- kiva/gl/__init__.py
- kiva/pdf.py
- kiva/ps.py
- kiva/qpainter.py
- kiva/quartz/ABCGI.pyx
- kiva/svg.py
- kiva/tests/test_qpainter_drawing.py
This adds `Image` from the Python Imaging Library as an acceptable argument for `draw_image` on all relevant kiva backends. Further, it uses `Image` internally to handle conversion of color modes to something which is compatible with the color mode of the graphics context.
Fixes #574
> Accept a PIL Image as input to draw_image()

- enable/examples/demo/enable/hidpi_component.py
This is a simple example which shows two `Component`s side-by-side. One has `high_resolution=False` for its `ComponentEditor`, showing that an application can mix and match HiDPI components as needed.
> Add an example of controlling HiDPI usage

- docs/source/conf.py
- docs/source/enable_concepts.rst
- docs/source/enable_constraints_layout.rst
- docs/source/enable_toolkit_selection.rst
- docs/source/index.rst
The banner feature here is an explanation of the `ETS_TOOLKIT`/`ETSConfig.toolkit` mechanism for selecting the GUI toolkit and kiva backend used by an application. In addition to that, I made some minor additions/modifications in other parts of the documentation.
> Add documentation for toolkit/backend selection

- ci/edmtool.py
Celiagg 1.1.1 breaks text rendering on Windows. Until that's fixed, we should pin the installed celiagg version to the previous release (1.0.3).
> Pin celiagg to a working version

- enable/wx/celiagg.py
Looking towards #414, we should have a celiagg backend for Wx. This PR supplies one.
> Add a celiagg kiva backend for Wx

- enable/abstract_window.py
- enable/tests/test_component_editor.py
> Don't mess up the component bounds in HiDPI mode

- ci/edmtool.py
- kiva/celiagg.py
Celiagg 2.0.0 was _just_ released. It fixes the text rendering bugs introduced by 1.1.1. Once it's available in EDM, this can be merged.
> Update celiagg backend to use 2.0.0 API

- .github/workflows/bleeding-edge.yml
The cron job is still broken because it was trying to get SWIG from PyPI. The correct source for SWIG is `apt-get`.
And after one test run, `celiagg` also needs to be installed but we can get that from PyPI.
> Install SWIG with apt-get

- CHANGES.txt
- setup.py
The cherry-picks in #640 are sufficient for a patch release, so here it is.
> Release 5.0.1

- docs/source/index.rst
- docs/source/kiva/backends.rst
> Document the available kiva backends

- kiva/qpainter.py
This is a bit of a drive-by fix. While testing #605 and comparing to the `kiva.qpainter` backend, I realized that it was ignoring bold and italic preferences for fonts. This corrects that, such that the `style` attribute of a `Font` is now honored.
> Fix font selection in the QPainter backend

- docs/source/kiva/quickref.rst
- kiva/abstract_graphics_context.py
- kiva/basecore2d.py
Most, but not all of #618. This nearly covers all the methods of GraphicsContext.
> Update the Kiva GraphicsContext documentation

- enable/gcbench/__main__.py
- enable/gcbench/bench.py
- enable/gcbench/publish.py
- enable/gcbench/suite.py
This is a small program which collects timing information for key drawing methods of `GraphicsContext` for each [available] backend and then optionally generates a report in HTML format.
I'd like to continue to improve this program, but I wanted to keep this initial PR under 500 LOC. Ideas for future improvements:
* Add hyperlinks for the image outputs written by each benchmark to the timings table
* "Benchmark" the non-UI backends to get a clearer picture of feature coverage.
* Add a GitHub action which generates this report and adds it to the documentation site so that we can get an idea about relative performance over time.
* Don't ignore the GL backend.
> Add a benchmark program for kiva graphics contexts

- ci/edmtool.py
This solution is lifted directly from traitsUI.
Previously running `python ci/edmtool.py test-all` would only run the test suite on one (randomly chosen - first item in a set) toolkit.  Now all toolkits are run.
> fix edmtool test-all command

- enable/savage/compliance/comparator.py
- enable/savage/compliance/crosshair.py
- enable/savage/compliance/sike.py
- enable/slider.py
- enable/text_grid.py
- enable/viewport.py
part of #416 
This PR replaces all uses of the `@on_trait_change` decorator with the observe equivalent.
> Convert on_trait_change decorators to observe

- enable/gcbench/publish.py
> Add links to benchmark image outputs

- enable/gcbench/bench.py
- enable/gcbench/opengl.py
Fixes #652
This wasn't as hard as I thought it would be. I just stole code from the kiva drawing tests.
> Add OpenGL support to the benchmark program

- kiva/qpainter.py
> Fix QPainter fill_path

- enable/gcbench/bench.py
- enable/gcbench/publish.py
Mentioned on #651, but there's no issue.
> Add a page for comparing backend outputs

- enable/gadgets/vu_meter.py
- enable/primitives/image.py
- enable/savage/compliance/comparator.py
- enable/text_field.py
- enable/tools/drag_tool.py
- kiva/examples/kiva/kiva_explorer.py
last part of #416 
This PR replaces all uses of `depends_on` in properties with `observe`.
> Replace depends_on with observe in properties

- enable/gcbench/bench.py
- enable/gcbench/pdf.py
- enable/gcbench/publish.py
Resolves #650
As you can see, there's something wrong with the PDF backend. That can be fixed elsewhere. Additionally, the code for writing the HTML output is getting really awful. It could benefit from some clean up if we think we might add any more enhancements.
> Run the kiva benchmark on all backends

- enable/gcbench/bench.py
- enable/gcbench/data.py
- enable/gcbench/publish.py
#666 was pretty exhausting to implement because of all the output differences introduced by non-GUI backends.
This is a general cleanup of the benchmark code, with emphasis on the `publish` function and introducing some real objects for the result data to hopefully make things a little more readable.
After this, I think the only thing left is to increase the size of the suite (ala #667) and _more importantly_, use the results as guidance for fixing problems and harmonizing backend outputs.
> Clean up the benchmark suite

- enable/gcbench/publish.py
fixes #670
#666 broke gcbench on windows. The fix is to simply set `encoding` when writing the gcbench output.
> Set encoding when writing gcbench output

- enable/gcbench/suite.py
I alluded to this in my feedback on #667. This PR removes the deferred imports from `enable.gcbench.suite` and leaves a helpful note for any future coders who want to add an import there.
Also included is a drive-by change of the `show_text_radial_gradient` benchmark which shows that celiagg is doing it correctly (or at the very least how I expect):
> Clean up the benchmark suite code

- kiva/quartz/ABCGI.pyx
- kiva/tests/drawing_tester.py
- kiva/tests/test_quartz_drawing.py
`save()` doesn't work at all currently. Implement the buffer interface and use `PIL.Image.frombuffer()`
> Fix save() in the quartz backend

- enable/gcbench/bench.py
- enable/gcbench/data.py
- enable/gcbench/publish.py
- enable/gcbench/suite.py
Working on #593 led me to this more uniform output for the benchmark suite. All output images appear to be the same size now, but the 2x ones are just crisper. Additionally, the 1x images are completely covered by whatever gets drawn.
> Handle 2x benchmark rendering more elegantly

- kiva/pdf.py
- kiva/svg.py
Font lookup was a bit screwy with all of the file-based Kiva backends. This fixes `set_font` for PDF and SVG, at least with respect to the benchmark program.
> Fix set_font() for PDF and SVG backends

- enable/qt4/quartz.py
Closes #516
This PR switches the Qt Quartz backend from a Window-based GC to an offscreen GC, because the changes in Qt5 make it very difficult (or impossible?) to reuse the `CGContextRef` from Qt's widget.
> Get the Qt Quartz backend working again

- docs/source/index.rst
- docs/source/kiva/images.rst
> Document image drawing in Kiva

- kiva/agg/src/graphics_context.i
- kiva/cairo.py
- kiva/celiagg.py
- kiva/pdf.py
- kiva/ps.py
- kiva/qpainter.py
- kiva/quartz/ABCGI.pyx
- kiva/svg.py
- kiva/tests/drawing_tester.py
- kiva/tests/test_agg_drawing.py
- kiva/tests/test_celiagg_drawing.py
- kiva/tests/test_quartz_drawing.py
> Supply DPI when saving images

- enable/tests/test_kiva_graphics_context.py
- kiva/agg/src/graphics_context.i
- kiva/examples/kiva/image_explorer.py
> Accept PIL Image instances in kiva.agg draw_image()

- docs/source/kiva/state.rst
> Document how colors work in Kiva

- enable/tools/pyface/api.py
> Add ContextMenuTool to enable.tools.pyface.api

- enable/api.py
- enable/brush.py
- enable/examples/demo/enable/brush_draw.py
- enable/examples/demo/enable/gradient_demo.py
- enable/tests/test_brush.py
These are classes intended to make it easier to paint and style filled regions.  This PR simply adds the classes and an example of usage.
Subsequent PRs will integrate this into existing code (eg. to add a background brush class to the base component).
> Add Brush classes

- kiva/fonttools/_constants.py
- kiva/fonttools/_scanner.py
- kiva/fonttools/_util.py
- kiva/fonttools/tests/test_scanner.py
NOTE: This does not _yet_ modify the behavior of `FontManager`.
This PR is intended to isolate the font file scanning code currently in `kiva.fonttools.font_manager` and cover it with tests. In a future PR, we'll actually start using this code.
Tangentially related to #391 and #555
> Move the font scanning code into private modules

- kiva/fonttools/_scan_parse.py
- kiva/fonttools/_scan_sys.py
- kiva/fonttools/tests/test_scan_parse.py
- kiva/fonttools/tests/test_scan_sys.py
> Split kiva.fonttools._scanner into two modules

- enable/null/oldagg.py
- enable/qt4/oldagg.py
- enable/wx/oldagg.py
- kiva/oldagg.py
This is step 3 from #414. Before switching the `image` kiva backend to celiagg, we need to make `kiva.agg` accessible via an unambiguous name.
> Add an 'oldagg' backend pointing to kiva.agg

- kiva/fonttools/_scan_parse.py
- kiva/fonttools/_util.py
- kiva/fonttools/tests/test_scan_parse.py
This fixes the font properties bugs pointed out by #391, but since it's happening in the refactored font code the issue remains open.
The core change here is to make `get_ttf_prop_dict` better.
Before:
```python
In [3]: font = TTFont("/Library/Fonts/Times New Roman Bold.ttf")                
In [4]: get_ttf_prop_dict(font)                                                 
Out[4]: {'name': 'Times New Roman', 'sfnt4': 'Times New Roman Bold'}
```
After:
```python
In [3]: font = TTFont("/Library/Fonts/Times New Roman Bold.ttf")                
In [4]: get_ttf_prop_dict(font)                                                 
Out[4]: 
{'copyright': '© 2006 The Monotype Corporation. All Rights Reserved.',
'family': 'Times New Roman',
'style': 'Bold',
'unique_subfamily_id': 'Monotype:Times New …
```
> Extract a better property dict from TTF fonts

- ci/edmtool.py
- docs/source/kiva/quickref.rst
Fixes #696
I also added `:noindex:` directives to all the methods in `kiva/quickref.rst` because the duplication was causing a bunch of warnings.
> Ignore kiva backends in the API docs

- kiva/fonttools/_constants.py
- kiva/fonttools/_font_properties.py
- kiva/fonttools/tests/test_font_properties.py
More font manager reorganization. This is the last big chunk to be copied out of `kiva.fonttools.font_manager`. The next step is to delete all the now duplicated code.
> Split FontProperties out into its own module

- kiva/fonttools/_constants.py
- kiva/fonttools/font_manager.py
These constants weren't moved in #701, so doing it here will reduce the noise of the upcoming code purge PR.
> Move some constants not yet moved

- kiva/fonttools/_score.py
- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/test_score.py
Ok, I'm pretty sure that along with #700, I'm really done breaking things out of `kiva.fonttools.font_manager`. The next PR is the big one.
This PR moves the font scoring methods to their own module and covers them _liberally_ with tests. A bug in `score_size` was fixed (trying to call a `dict` instance).
The font scoring methods are used by `FontManager.findfont` to compare `FontEntry` instances with `FontProperties` instances to determine their similarity.
> Break out the font scoring methods and test them

- MANIFEST.in
- kiva/fonttools/LICENSES/LICENSE_fonttools
- kiva/fonttools/_scan_parse.py
- kiva/fonttools/tests/data/TestAFM.afm
- kiva/fonttools/tests/test_scan_parse.py
- kiva/fonttools/tests/test_scan_sys.py
- setup.py
`kiva.fonttools.afm` should not exist. Once all this font chaos is done, it won't.
This PR starts the ball rolling by changing the AFM parsing in the new code to use `fonttools.afmLib:AFM`. While I was at it, I copied `fonttools` test AFM file. Now we're actually exercising the code with some real data!
> Use fonttools.afmLib instead of ad-hoc AFM parser

- kiva/fonttools/tests/test_font.py
Checking the coverage before and after my refactor, I saw that `str_to_font` was not covered (at least when looking at `kiva.fonttools` in isolation). This PR corrects that.
> Add tests for str_to_font

- .github/workflows/bleeding-edge.yml
- .github/workflows/test-with-edm.yml
- ci/edmtool.py
- kiva/api.py
- kiva/fonttools/__init__.py
- kiva/fonttools/_scan_sys.py
- kiva/fonttools/app_font.py
- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/test_app_font.py
- kiva/fonttools/tests/test_scan_sys.py
- kiva/tests/test_gl_drawing.py
Closes #555
This works well with the QPainter and AGG backends. It does _not_ work with the Quartz backend. Also, I was not able to test this properly with Wx because the feature isn't supported in the wheel that I installed (perhaps it's a macOS thing?).
> Add a way for applications to supply custom fonts

- docs/source/enable/abstract_window.rst
- docs/source/index.rst
- enable/abstract_window.py
> Add documentation for AbstractWindow

- docs/source/enable/mouse_events.rst
- docs/source/index.rst
- enable/events.py
> Add documentation for mouse events

- enable/testing.py
- enable/tests/test_test_assistant.py
- enable/tests/tools/pyface/test_move_command_tool.py
- enable/tests/tools/pyface/test_resize_command_tool.py
fixes #460 
This PR adds `left_down` and `right_down` kwargs to `mouse_move` so that the test assistant can simulate moving the mouse with either the left or right button down.  As mentioned on the issue, there are cases where we expect mouse_move events to have {left/right}_down set to True.  This PR also adds a simple test to check that the traits are set if we call mousee_move with the new kwargs.  Additionally, the `press_move_release` method is updated so that `left_down` is True for the mouse_move generated event itself.
> Allow sending "mouse move" with left/right down with EnableTestAssistant

- enable/tests/test_drag_tool.py
- enable/tools/drag_tool.py
fixes #551 
It seems like this fix is going to require a change in behavior and may potentially "break" existing code.
Currently the `end_drag_on_leave` flag does not actually lead to a drag being "ended" on a mouse leave.  Instead it is canceled.  My thoughts were to either add a `cancel_drag_on_leave` trait to do what `end_drag_on_leave` currently does (ie cancel the drag) and change `end_drag_on_leave` to actually end (see first commit). However, this requires one of these having preference over the other if both are True, and in actuality you would only ever want one behavior, so I removed `end_drag_on_leave` and made a new `on_drag_leave` enum trait.
This however is a change in the public api so we need to tread very carefully.  I am unsure what exactly we want to go with here, and …
> Add new on_drag_leave Enum trait to DragTool

- docs/source/enable/traits.rst
- docs/source/index.rst
> Document Enable trait types

- kiva/fonttools/_database.py
- kiva/fonttools/_scan_parse.py
- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/test_font.py
- kiva/fonttools/tests/test_font_manager.py
- kiva/fonttools/tests/test_scan_parse.py
This will be useful to #711 (for avoiding duplicate additions).
Instead of using lists inside of `FontManager` to hold collections of `FontEntry` objects, this PR introduces a `FontDatabase` class which ensures all known entries are unique and provides a way to query entries by file path or font family in order to pare down the number of fonts that need to be scored by `FontManager.findfont`.
> Use a database object to manage fonts

- .gitignore
- MANIFEST.in
- kiva/_marker_renderer.pxd
- kiva/_marker_renderer.pyx
- kiva/api.py
- kiva/celiagg.py
- kiva/marker_renderer.py
- kiva/markers/LICENSES/LICENSE_Agg
- kiva/markers/agg/agg_array.h
- kiva/markers/agg/agg_basics.h
- kiva/markers/agg/agg_color_gray.h
- kiva/markers/agg/agg_color_rgba.h
- kiva/markers/agg/agg_config.h
- kiva/markers/agg/agg_dda_line.h
- kiva/markers/agg/agg_ellipse_bresenham.h
- kiva/markers/agg/agg_gamma_functions.h
- kiva/markers/agg/agg_gamma_lut.h
- kiva/markers/agg/agg_pixfmt_base.h
- kiva/markers/agg/agg_pixfmt_rgb.h
- kiva/markers/agg/agg_pixfmt_rgba.h
- kiva/markers/agg/agg_renderer_base.h
- kiva/markers/agg/agg_renderer_markers.h
- kiva/markers/agg/agg_renderer_primitives.h
- kiva/markers/agg/agg_rendering_buffer.h
- kiva/markers/agg/agg_trans_affine.h
- kiva/markers/marker_renderer.h
- kiva/tests/test_marker_rendering.py
- setup.py
Closes #708
This was surprisingly straightforward. Basically, since marker rendering is a much more primitive form of rendering, it's not too bad to just copy the subset of AGG which implements it.
As was the case with #392, there's a bunch of code from AGG here which is just copied in. Well, copied and given a new `agg24markers` namespace so that there's no danger of symbol collisions. (also LF line endings and stripped whitespace) You can basically ignore it for the purpose of reviewing and concentrate on the Python and Cython code.
I've added `draw_marker_at_points` to the celiagg backend to show what an implementation might look like.
> Create an independent renderer for draw_marker_at_points

- enable/qt4/celiagg.py
- kiva/celiagg.py
This makes some small changes to the celiagg backend so that a celiagg `GraphicsContext` looks a bit more like a `kiva.agg` `GraphicsContext`. This covers [this comment](https://github.com/enthought/enable/issues/414#issuecomment-737519739)  on #414 by adding a `bmp_array` attribute to celiagg's `GraphicsContext`. Additionally, "bgra32" is now the default pixel format.
> Make celiagg a little bit more like kiva.agg

- docs/source/enable/traitsui.rst
- docs/source/index.rst
- enable/component_editor.py
> Add documentation for ComponentEditor

- kiva/svg.py
fixes #734 
This PR fixes an issue with the SVG backend where saving to an image when running the enable benchmark was failing with an encoding issue. This was fixed by simply setting the encoding when saving the image.
> Set encoding when saving image from SVG backend.

- ci/edmtool.py
- kiva/celiagg.py
Fixes #643
Celiagg 2.1.0 introduces a new font object for win32 which allows specification of bold/italic styles.
> Add support for text styles on Win32+Celiagg

- ci/edmtool.py
- kiva/celiagg.py
- setup.py
Now that #643 is closed, it should be included in 5.1.0. I've also unset the `IS_RELEASED` flag until we're ready to cut rc2.
> Pick #726 into the 5.1.0 release branch

- kiva/tests/test_qpainter_drawing.py
Our Pillow requirement has been upgraded to version 7.2.0 in EDM. This version removed support for Qt4. To get CI working again, we should skip tests of QPainter drawing on Qt4.
> Don't test drawing on Qt4

- docs/source/enable/constraints_layout.rst
> Update constrained layout documentation

- enable/api.py
- enable/base.py
- enable/examples/demo/enable/filled_container_demo.py
- enable/examples/demo/enable/hidpi_component.py
Resolves #1 (it only took 10 years 😎)
> Deprecate the str_to_font in enable.base

- enable/abstract_window.py
- enable/tests/test_abstract_window.py
> Don't create a ref cycle in AbstractWindow.cleanup()

- kiva/abstract_graphics_context.py
> Mention return value for draw_marker_at_points

- enable/abstract_overlay.py
- enable/base_tool.py
- enable/tools/toolbars/viewport_toolbar.py
- enable/tools/viewport_zoom_tool.py
Fixes #736
Fixes #737
Fixes #739
@corranwebster I see that `ViewportToolbar` and `ViewportZoomTool` also have `component=None` in their `__init__` method signatures.
> Clarify __init__s which allow `component` as a pos. arg.

- kiva/agg/src/graphics_context.i
- kiva/tests/drawing_tester.py
- kiva/tests/test_agg_drawing.py
Resolves #750
This is basically the same change as celiagg/celiagg#97, but with SWIG exception handling instead of Cython. A test has also been added to show that the error is now recoverable.
(Celiagg keeps its rasterizer instance around between draw calls, so it needed an additional change to the AGG code which is not needed here)
> Catch the exception thrown by AGG

- enable/__init__.py
- setup.py
Resolves #486
I didn't do this exactly like TraitsUI (as suggested in the issue). Instead, I opted to use `runpy.run_path` everywhere.
> Don't try to import from enable in setup.py

- CHANGES.txt
As mentioned in #756, the changelog needs to be updated to reflect the full contents of 5.1.0
> Update changelog to match 5.1.0 branch

- kiva/_profiler.py
- kiva/profiler.py
This has been sitting around in my local repository for a bit, so I decided to clean it up and push it.
With this function `instrument_graphics_context`, it's possible to add a little bit of code to the `Window` implementation of a backend so that it outputs profiler results for every paint of a `ComponentEditor`. So far I've used it to get a feel for drawing speed in a complex application and also to help speed up text rendering changes in celiagg.
Here's an example of the changes needed to profile the `qt.celiagg` toolkit+backend. 
```diff
index 73fc9057..acc654a3 100644
--- a/enable/qt4/celiagg.py
+++ b/enable/qt4/celiagg.py
@@ -10,12 +10,15 @@
import numpy as np
from kiva.celiagg import CompiledPath, GraphicsContext  # noqa
+from kiva.profiler import instrument_graphics_context
from …
```
> Add a way to profile calls to GraphicsContext

- docs/source/conf.py
- docs/source/kiva/drawing_details.rst
- docs/source/kiva/font_manager.rst
- enable/api.py
- enable/drawing/api.py
- enable/layout/layout_helpers.py
- enable/primitives/api.py
- enable/trait_defs/rgba_color_trait.py
- kiva/api.py
- kiva/trait_defs/kiva_font_trait.py
Doing a full build of the documentation with autodoc generation was spitting out some warnings, so I squashed them.
> Fix warnings from the documentation build

- enable/scrolled.py
This PR fixes two listeners that are hooked up using `observe` but are then unhooked using `on_trait_change`.
> Fix listeners hooked up using observe but unhooked using on_trait_change

- kiva/fonttools/text/_language.py
- kiva/fonttools/text/_unicode_lookup.py
- kiva/fonttools/text/tests/test_unicode_lookup.py
This is another step for #762
The PR adds support for converting the script name generated by `UnicodeAnalyzer` and mapping it to a language name which a font reports support for.
> Create a mapping from script to font language

- kiva/fonttools/_database.py
- kiva/fonttools/font.py
- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/test_font.py
This is a big part of #762: Give a way to lookup a font which "matches" a query and supports a particular language. Builds on top of the work done in #763
> Add support for font fallback lookups

- enable/gcbench/bench.py
- enable/null/blend2d.py
- kiva/blend2d.py
This is a bit experimental and unfinished, mostly due to the incomplete state of the blend2d-python wrappers. That said, there's some promise here. I'm only exposing the backend via the `null` toolkit, but it's covered by the `enable.gcbench` suite. It fails most of the benchmarks. But its performance for the `draw_path` benchmark should encourage us to fill out the remaining functionality and see how it stacks up against the other backends.
> Create a Blend2D Kiva backend

- enable/api.py
This PR re-exports the `HStackedContainer` and `VStackedContainer` classes via the `enable.api` module. The need arises from https://github.com/enthought/chaco/pull/674.
> Expose "HStackedContainer" and "VStackedContainer" via "enable.api"

- docs/source/enable/overview.rst
- enable/component.py
fixes #775 
See corresponding issue/PR in chaco: https://github.com/enthought/chaco/issues/659, https://github.com/enthought/chaco/pull/671
This PR simply removes the now unneeded check of `use_draw_oder` and simply fills the body of `dispatch` with what used to be `_new_dispatch`.  `_old_dispatch` is deleted.
> Remove "use_draw_order" code path

- enable/markers.py
This PR converts `#` comments for traits to `#:` comments to improve the documentation in the `enable.markers` module. This PR also removes unnecessary trait definitions `antialias` for some markers which don't modify the default that they inherit from `AbstractMarker`.
> Convert # to #: to improve docstrings in markers

- enable/stacked_container.py
This PR fixes the alignment trait and `_do_layout` method on the `HStackedContainer`. This might have been a simple copy-paste mistake. This was discovered when working on https://github.com/enthought/chaco/pull/674.
This PR simply renames the `halign` triat with `valign` and updates its usage in the `_do_layout` method. See related https://github.com/enthought/chaco/blob/a88b7b96a981dc96ad9f0d615c21d699f93851d1/chaco/plot_containers.py#L289-L324, which is possibly where the `HStackedContainer` class originated.
> Fix alignment trait on "HStackedContainer"

- enable/api.py
- enable/base.py
- kiva/agg/__init__.py
- kiva/tests/test_points_in_polygon.py
This PR removes the deprecated `str_to_font` from `enable.api` and `points_in_polygon` from `kiva.agg`.
> Remove deprecated "str_to_font" and "points_in_polygon" functions.

- enable/api.py
closes #772 
This PR simply re-exports `CompiledPath` and `font_metrics_provider` in `enable.api`
> add CompiledPath and font_metrics_provider to enable.api

- enable/canvas.py
- enable/tests/tools/test_hover_tool.py
- enable/text_grid.py
See related #789 
This PR updates a few calls to `super` that were potentially buggy. In these two cases for example, we were calling `super(A, self)` from class `B` where `B` inherits from `A`. We first update the `super` calls to use the correct class argument - and then update the `super` call to remove the arguments altogether.
> Update super usage in potentially buggy cases

- enable/markers.py
- enable/tests/test_markers.py
Needed to close https://github.com/enthought/chaco/issues/232
Down in agg the method that gets called wants double inputs.  If an int gets passed it things break.  Changing the inputs to floats seems to resolve the problem.
> Update custom marker as scale_ctm expects floats

- enable/stacked_layout.py
Ref ~https://github.com/enthought/chaco/pull/673/~. https://github.com/enthought/chaco/pull/673 got closed in favor of https://github.com/enthought/chaco/pull/674
It looks like these lines were commented out from the original commit when this code was added to enable in https://github.com/enthought/enable/commit/75fb3ac9e478751992865d98d8f27791e7a988df
and subsequently, the commented out code was removed in the PR #466
> Handle preferred size computation when container isnt resizable

- enable/tests/test_markers.py
Previously the test was skipped when not on qt.  This worked because it avoided the scenario of using quartz as tthe default backend on wx.  See:
https://github.com/enthought/traits/blob/249d64813b633390616af4e57ceb19a553c250ef/traits/etsconfig/etsconfig.py#L313-L320
Realistically, these tests are specific to the old agg. see comment: https://github.com/enthought/enable/pull/782#issuecomment-825074184
Note we can't yet skip if not "oldagg" because oldagg isn't actually used yet.  Doing so the test would no longer be run.  I left a comment to replace 'image' with 'oldagg' in the `skipIf` once `image` uses celiagg.
> Skip markers tests if not using agg

- enable/container.py
closes #792 
This PR simply removes the deprecated `intercept_events` trait on Container
> remove deprecated intercept_events trait on Container

- kiva/trait_defs/ui/wx/kiva_font_editor.py
Closes #803 
This PR directly follows the migration guide linked in the issue: https://wxpython.org/Phoenix/docs/html/MigrationGuide.html#font-pen-and-brush-styles
> use non deprecated font families styles etc

- enable/savage/compliance/viewer.py
closes #802 
As mentioned on the issue, this PR follows migration described here: https://wxpython.org/Phoenix/docs/html/MigrationGuide.html#wx-treectrl
> Replace use of deprecated GetItemPyData with its new replacement GetItemData

- kiva/agg/src/gtk1/plat_support.i
- kiva/agg/src/win32/plat_support.i
- kiva/agg/src/x11/plat_support.i
This PR removes the old/outdated/unnecessary `draw_to_tkwindow` drawing code in the platform support for the agg backend.
> Remove unused tk related drawing methods

- pyproject.toml
1st part of #769 
This PR simply includes a `pyproject.toml` file specifying `cython` and `numpy` as build dependencies.  
I ran `python setup.py sdist`, created a fresh environment and ran `pip install enable-5.1.0.dev280.tar.gz`
previously I saw:
```
$ pip install enable-5.1.0.dev280.tar.gz
Processing ./enable-5.1.0.dev280.tar.gz
ERROR: Command errored out with exit status 1:
command: /Users/aayres/.edm/envs/dumb/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j9/ps8s26f91_1_lgf7mtd4smyr0000gn/T/pip-req-build-e1pybp8n/setup.py'"'"'; __file__='"'"'/private/var/folders/j9/ps8s26f91_1_lgf7mtd4smyr0000gn/T/pip-req-build-e1pybp8n/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', …
```
> Add pyproject.toml to specify cython and numpy as build deps

- kiva/quartz/mac_context.c
This PR removes a use of `PY_MAJOR_VERSION` conditional in the quartz backend c extension code. The Python 2 branch has been removed while preserving the Python 3 branch.
> Remove an "PY_MAJOR_VERSION" conditional in quartz backend

- enable/component.py
- enable/container.py
closes #794 
closes #781 
This PR removes the `_draw_component` methods on `Container`/`Component` as well as the `_draw_overlays` (note `_draw_overlay` is still around) and `_draw_children` methods on container.
> Remove old deprecated drawing methods

- enable/abstract_window.py
closes #812
This PR simply removes the old deprecated trait.  Note searching the codebase for `bg_color` is what motivated issue #815. Perhaps `enable/trait_defs/ui/wx/enable_rgba_color_editor.py` should just be deleted?  given 815 I imagine it is completely broken
> Remove AbstractWindow.bg_color trait

- CHANGES.txt
The changelog for 5.0.1 release is in the maintenance branch but not on the main branch. This PR backports the changelog.
> Backport changelog for 5.0.1 release

- enable/qt4/cairo.py
- enable/qt4/celiagg.py
- enable/qt4/image.py
- kiva/cairo.py
Closes #819
The issue is tested (manually) to affect these backends: `qt4.image`, `qt4.celiagg` and `qt4.cairo`.
For these backends, the `GraphicsContext` is defined to be slightly larger than the requested size:
https://github.com/enthought/enable/blob/1c3805cdf8e47085a2ae91cdcdc2ed0d12ba33e6/enable/qt4/cairo.py#L20-L23
There is another `QRectF` defined for `qt4.quartz`, but I could not reproduce the issue there. For this backend, the GraphicsContext was defined without the plus-one:
https://github.com/enthought/enable/blob/685038503500ecf8ffc30f3da68c7e848ae02e6f/enable/qt4/quartz.py#L35
Note that `base_scale` was not defined on the `GraphicsContext` for the cairo backend, and so it has to be added.
Apparently `base_scale` is not defined on the `qpainter`'s `GraphicsContext` either, but …
> Fix artefact in Qt caused by QRectF having a slightly wrong size

- CHANGES.txt
- enable/qt4/cairo.py
- enable/qt4/celiagg.py
- enable/qt4/image.py
- kiva/cairo.py
This PR backports the PR #820 to the `maint/5.1` branch in preparation for the bug-fix release enable 5.1.1
Note : As you can see, it looks like the enable 5.1.0 changelog is missing from the maintenance branch - which will be addressed in a separate PR.
> Backport PR #820 to the 5.1 maintenance branch in preparation for enable 5.1.1

- CHANGES.txt
As mentioned on #822 
The changelog entries for 5.0.1 and 5.1.0 were missing from `maint/5.1`.  This PR simply pulls those updates from master.
> Pull in older changelog updates from master

- setup.py
Targeting `maint/5.1`
This PR bumps the release version and flip the IS_RELEASE flag for the development of the next bug fix release.
> Bump version and set IS_RELEASED to False for development of 5.1.2

- docs/source/conf.py
- docs/source/enable/testing.rst
- docs/source/index.rst
closes #774 
This PR adds a brief section to the documentation describing the `EnableTestAssistant`.  This is effectively meant as a starting point, and we will likely want to expand this documentation going forward.  In any case, just mentioning its existence in the docs is a significant improvement over it being missing entirely.
A next step (in a future PR) would be to add an example test using the test assistant to showcase how to use it and some of the useful features.  I was going to simply link to an existing test, but none of them felt really suited to be a good example for the documentation IMO.  I think it will be useful to write a test specifically for the docs, possibly writing a test for on of the existing examples.
> Document EnableTestAssistant

- CHANGES.txt
[targeting `maint/5.2`]
The updates for 5.1.1 were not yet pulled into master, so they are added here as well.
This PR updates the changelog for the upcoming 5.2 release candidate. Any additional changes made after the candidate but before the release will be added in future PR if needed.
> Update changelog in prep for 5.2.0 release candidate

- enable/__init__.py
This has actually been true since PR #507 
Adding it now simply to be more explicit
> Explicitly require pyface>=7.2 since we use pyface.undo

- setup.py
This branch name is poorly named - this PR does not bump the version, it simply sets `IS_RELEASED` back to false for continued development of 5.2.0 in prep for the full release.
> Flip IS_RELEASED back to False

- setup.py
The merge commit from this PR will be tagged as the 5.2.0 release candidate (this time for real)
> Enable Release Candidate 5.2.0rc2

- enable/abstract_window.py
- enable/scrolled.py
closes #795 
This PR simply replaces the use of `__getstate__` methods by setting `transient` metadata on relevant traits.  `HasTraits` handles this with its own `__getstate__` method appropriately.
EDIT: It also removes the unused `_scroll_origin` attribute on `AbstractWindow`.
> remove __getstate__ methods and use transient metadata

- enable/stacked_container.py
Ref:
https://github.com/enthought/chaco/pull/764#discussion_r646830361
Also see the `__getstate__` methods defined on `HPlotContainer` and `VPlotContainer` in that PR.
> Set transient metadata and pull up __getstate__ method

- enable/abstract_window.py
- enable/scrolled.py
- enable/stacked_container.py
These two PRs were recently merged into master but can be included in the 5.2.0 release.
> Backport recent PRs to maintenance branch

- pyproject.toml
fixes #846 using the same approach as https://github.com/enthought/chaco/pull/779
We will want to backport this to `maint/5.2` prior to the 5.2.0 release.
> use oldest-supported-numpy in pyproject.toml

- kiva/agg/src/font_type.i
- kiva/agg/src/graphics_context.i
- kiva/gl/src/swig/font_type.i
This PR removes 2 more code branches that supported Python 2. These code branches were hard to discover because they checked if a string is equal to a bytestring (`'' == b''`) - which is only true on Python 2 and not on Python 3. Note that these were discovered when looking at #839
> Remove more code branches that supported Python 2

- CHANGES.txt
- pyproject.toml
This PR backports the recent `pyproject.toml` fix to the `maint/5.2` branch, and also updates the changelog with that PR, PR #836 which was recently merged into the `maint/5.2` branch directly, and the PRs #804 and #841 which were backported to the maint branch in #845
> pyproject.toml fix backport and changelog updates

- .github/workflows/test-with-edm.yml
Part of https://github.com/enthought/ets/issues/57
This PR removes CI testing against pyqt4
> Dont test with pyqt4 on CI

- enable/tests/test_viewport.py
This PR removes an unnecessary use of `print(...)` that adds a bit of noise to the testsuite.
> Remove an unnecessary print call from the testsuite

- setup.py
This PR simply bumps the version number in setup.py for continued development.
> Bump version and set IS_RELEASED to False for development of 5.2.1

- ci/edmtool.py
PR #851 stops testing against PyQt4 on CI so this PR removes support for PyQt from the CI helpers i.e. `ci\edmtool.py`
> Remove support for PyQt in ci helpers

- kiva/agg/src/font_type.i
- kiva/agg/src/graphics_context.i
- kiva/agg/tests/test_affine_matrix.py
- kiva/gl/src/swig/font_type.i
Fixes #360.
The Swig wrappers used a historic construct (using `_swig_setattr` instead of direct attribute assignment) that broke with the relase of Swig 4 (which removed `_swig_setattr`). 
There are a lot of historical oddities with the Swig wrappers (as is well-known); I didn't touch anything beyond the strictly necessary, expecting the Swig layer to go away with #414.
> Make Kiva compileable with Swig 4

- CHANGES.txt
Looks as though the changes for 5.1.1 were never pulled into the changelog on master either.
This PR simply copies the updated changelog from the `maint/5.2` branch back into master.
> Update changelog with 5.1.1 and 5.2.0

- setup.py
Replaces #861, via fork.
Instead of disabling the check for Swig altogether, just checks that Swig is installed, without checking the version.
> Fix swig check setup

- .github/workflows/bleeding-edge.yml
This PR makes it possible to manually trigger the cron job - using `workflow_dispatch`. Ref https://github.com/enthought/ets/issues/68
> Make it possible to manually trigger cron job

- CHANGES.txt
targeting `maint/5.2`
This PR simply updates the changelog in prep for 5.2.1
> update changelog in advance of 5.2.1

- kiva/tests/drawing_tester.py
There was a recent `pillow` release which included this change: https://github.com/python-pillow/Pillow/pull/5476
That was causing the cron job to fail with:
```
======================================================================
FAIL: test_save_dpi (kiva.tests.test_agg_drawing.TestAggDrawing)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/kiva/tests/test_agg_drawing.py", line 24, in test_save_dpi
self.assertEqual(self.save_and_return_dpi(), 144)
AssertionError: 143.99259999999998 != 144
======================================================================
FAIL: test_save_dpi (kiva.tests.test_celiagg_drawing.TestCeliaggDrawing) …
```
> Fix the dpi related cron job failures

- CHANGES.txt
- kiva/tests/drawing_tester.py
targeting `maint/5.2`
This PR backports the recent fix of the cron job failures to the maintenance branch so it can be included in the 5.2.1 bugfix release.  It also updates the changelog
> Backport cron job fix

- CHANGES.txt
This PR cherrypicks the commits made to the `maint/5.2` branch updating the changelog for the 5.2.1 bugfix release back to master.
> Backport changelog updates from 5.2.1 release

- setup.py
This PR simply bumps the version after the 5.2.1 bug fix release for continued development.
> Bump version and set IS_RELEASED to False for development on 5.2.2

- .github/workflows/bleeding-edge.yml
- CONTRIBUTING.rst
- ci/edmtool.py
This PR replaces the use of ``master`` in the repo with ``main`` as the default branch has been renamed.
>  Default branch has been renamed from "master" to "main"

- .github/workflows/test-with-edm.yml
- ci/edmtool.py
This PR updates the CI to use `ubuntu-18.04`, not `ubuntu-16.04` as it is no longer available on GitHub Actions CI. Accordingly, we also install the necessary `libsdl`.
> Test on ubuntu-18.04, not 16.04

- enable/__init__.py
- enable/savage/svg/pathdata.py
- enable/savage/svg/tests/test_pathdata.py
fixes #887 
This PR fixes an issue because of an upstream change with the `pyparsing` `CaselessLiteral` class, where the `name` attribute became a read-only property in version >= 3. We now use the new public `set_name` method instead of directly setting the attribute.
Confusingly, this isn't documented in the API changes section of the documentation - https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_0_0.html#api-changes but it can be found by digging into the codebase https://github.com/pyparsing/pyparsing/blob/0352555d968f9952800f0728383de8e1f9526e1e/pyparsing/core.py#L1802-L1805. Note that `CaselessLiteral` inherits from `Token` which in turn inherits from `ParserElement`, which contains the property `name` and the new `set_name` public API.
Note to reviewer : I tested …
> Fix svg backend issue with pyparsing version >= 3

- .github/workflows/test-with-edm.yml
- ci/edmtool.py
- enable/savage/svg/pathdata.py
- enable/savage/svg/tests/test_pathdata.py
This PR backports PR #888 and #889 to the `maint/5.2` maintenance branch. Once this PR is merged, we will be able to make a 5.2.2 bugfix release. Note : We'll be able to make a release not that we're planning to.
> Backport PRs #888 and #889 to 5.2 maintenance branch

- kiva/tests/agg/test_text.py
This attempts to set the locale to the current value before changing to the testing locale to ensure that a reset will work.  On failure, it skips which matches previous behaviour.
Fixes #899
> Fix text locale test issue on Windows

- kiva/fonttools/_util.py
I think this happens for either very old fonts or fonts which aren't fully compliant with the open type specification.  Not much either we or the user can do about it, so we just ignore - the information we want isn't there.
We could write a test if we can find a font which is missing this piece of data and has a suitable license (eg. OTL).  However the only fonts I could find with this are [Humor sans 1.0](http://xkcdsucks.blogspot.com/2009/03/xkcdsucks-is-proud-to-present-humor.html) which is unlicensed and MTExtra which is owned by Microsoft and which is not suitably licensed.
A reviewer can validate that this PR works by:
- having either Humor Sans or MTExtra installed in their test system
- clearing out ~/.enthought/kiva (or the corresponding directory on Windows)
- running some code …
> Handle .ttf fonts with missing `ulCodePageRange1` entries

- ci/edmtool.py
- enable/__init__.py
- kiva/tests/test_graphics_context.py
The use of Hypothesis was just to repeat a test with different values. Replacing with subTest is straightforward.
Fixes #881.
> Replace use of Hypothesis with subTest

- kiva/celiagg.py
- kiva/tests/test_celiagg_drawing.py
> Sanity check dash arguments

- enable/drawing/point_line.py
- enable/tests/drawing/test_point_line.py
> Use correct trait type for mouse pointers

- enable/qt4/base_window.py
- enable/qt4/constants.py
- kiva/gl/__init__.py
The `QOpenGLWidget` replaces the deprecated `QGLWidget`.  The only change is that we no longer need to actively call `swapBuffer`.
This PR relies on #897 being merged first, since this can't be tested on Qt6 without that PR.
> Use `QOpenGLWidget`

- docs/source/index.rst
- docs/source/kiva/drawing_details.rst
- docs/source/kiva/font_manager.rst
- docs/source/kiva/overview.rst
- docs/source/kiva/writing_a_backend.rst
- kiva/fonttools/font_manager.py
In particular, this:
- adds many links to the API documentation
- fixes #869
- adds a stub document discussing writing new Kiva backends
- clarifies wording in several places
> Updates and improvements to Kiva documentation

- enable/tests/trait_defs/test_rgba_color_trait.py
- enable/trait_defs/rgba_color_trait.py
This is very similar to the PyfaceColor Trait in Pyface, except that the value held is a RGBA tuple.
This makes a few changes in the way that colors are parsed, using the parser from Pyface which is a but more accepting in what it recognizes, but should match all color names (since the Pyface names were copied from Enable).  It also will accept a Pyface `Color` object and convert it to a tuple.
Part of #417, also relevant for #913 (but not all that is needed).
> Replace RGBAColor Trait with something more modern.

- enable/qt4/base_window.py
- enable/tests/qt4/test_mouse_wheel.py
This fixes #915 but additionally will fix code from other Qt mouse events, since the position API has changed - there are no longer `x` and `y` position getters available in Qt6.
This:
- uses the new API for position for Qt6 mouse events
- fixes the test code that generates synthetic mouse events for Qt6
> Fix Qt6 mouse event code

- enable/colors.py
- enable/component_editor.py
- enable/examples/_example_support.py
- enable/tools/hover_tool.py
- enable/trait_defs/ui/rgba_color_editor.py
- kiva/fonttools/app_font.py
- kiva/trait_defs/kiva_font_trait.py
In a number of places the code used ETSConfig.toolkit to determine the backend at import time.  However it is possible that that value was being checked before ETSConfig.toolkit was properly set.  This changes the code to get the appropriate Pyface or TraitsUI toolkit object and gets the name of the toolkit from that.
This fixes #913.
This doesn't attempt to fix #904.
> Ensure toolkit is initialized before use

- enable/abstract_window.py
- enable/canvas.py
- enable/component.py
- enable/drawing/drag_box.py
- enable/enable_traits.py
- enable/interactor.py
- enable/markers.py
- enable/primitives/line.py
- enable/primitives/polygon.py
- enable/qt4/scrollbar.py
- enable/slider.py
- enable/tests/test_enable_traits.py
- enable/text_grid.py
- enable/tools/viewport_zoom_tool.py
- enable/wx/scrollbar.py
This largely removes the usage of `Trait()` in the codebase.  The places where it is not changed are in `enable.color` (which is resolved by #924) and in the `KivaFontTrait` which is complex enough to deserve its own PR.
The PR was done in stages, each commit doing a different type of trait replacement (eg. Trait -> Union, Trait -> Map, etc.) so it may be easier to review one commit at a time.
Fixes #417.
> Remove usage of `Trait()`

- kiva/fonttools/font_manager.py
- kiva/fonttools/tests/test_font_manager.py
Closes #930. Fixes a typo in the default font filename
> FIX: Use correct path to the default font

- enable/examples/demo/enable/editors/font_editor.py
- enable/label.py
- enable/tests/trait_defs/test_kiva_font_editor.py
- enable/trait_defs/ui/api.py
- enable/trait_defs/ui/editor_with_component.py
- enable/trait_defs/ui/kiva_font_editor.py
This font editor is largely toolkit independent: it embeds a `Window` with a `Label` component to display the font and the simple editor uses the Pyface font dialog to get new font values.  It also includes some drive-by fixes to the `Label` component (eg. mis-drawn borders, not updating when size of widget changes).
There is a demo of the code in `enable/demo/enable/editors/font_editor.py`:
Some functionality is broken out into experimental base classes for building editors with components in the thought that those may be independently useful in the future.
Things not done:
- a custom editor with widgets that control styling, etc. independently
- better string font representation/parsing
- changes to the font trait itself
This is towards #922
> Add a new font-editor that uses Enable to draw fonts

- enable/tests/test_coordinate_box.py
The test methods in `CoordinateBoxTestCase` were not being executed. This PR renames the test methods so that they're identified as such by unittest.
Closes #936
> Rename CoordinateBoxTestCase test methods

- .github/workflows/bleeding-edge.yml
This PR updates the scheduled workflows to report failures to the main ETS channel rather than the more noisy bots channel, in the hope that they're more likely to be noticed there. Successes continue to be reported to the bots channel.
> Report cron job failures to main Slack channel, not bots channel

- kiva/agg/src/x11/plat_support.i
Addresses these warnings/exceptions:
- TypeError: BitmapFromImage() got an unexpected keyword argument 'depth'
- AttributeError: 'PaintDC' object has no attribute 'BeginDrawing'
- wxPyDeprecationWarning: Call to deprecated item EmptyImage. Use :class:`Image` instead.
image = wx.EmptyImage(*sz)
- wxPyDeprecationWarning: Call to deprecated item BitmapFromImage. Use :class:`wx.Bitmap` instead
bmp = wx.BitmapFromImage(image, depth=-1)
See https://forums.wxwidgets.org/viewtopic.php?t=39930 why the Begin/EndDrawing calls can simply be removed.
Related issues: #798 and enthought/chaco#531
> Get things working on wxPython again

- kiva/quartz/CTFont.pyx
- kiva/tests/_testing.py
- kiva/tests/test_quartz.py
Fixes #964.
Bytes seem to be assuming `mac-roman` encoding, so use that in decoder.
Also a drive-by fix to make quartz tests proper unittest tests rather than nose/pytest-style.
> Fix Kiva Quartz backend string encoding

- .github/workflows/publish-on-pypi.yml
This doesn't attempt to do any sort of building, just packages up the sdist.
PyPI secrets will need to be added for the project.
> Add a github workflow that publishes to sdists to PyPI on release

- kiva/svg.py
Fixes #979.
Benchmark now looks like this:
> Take into account all font features when drawing SVG text

- kiva/quartz/ABCGI.pyx
This looks up font family names if no specific face name is given, and switches rendering of text to use the fill color rather than the stroke color, to match Agg, etc. rendering.
Font rendering benchmark now looks like this:
Fixes #976.
> Fix Quartz font rendering

- kiva/fonttools/font.py
- kiva/fonttools/tests/test_font.py
Fix is a matter of having `Font.familymap` map to the right thing.  This is a _very_ old bug.
This is the benchmark rendering in the agg backend after the fix (note the "script" column):
Fixes #971.
> Fix `SCRIPT` font family in Kiva

- kiva/qpainter.py
This fixes #962 but not #960.
Anticlockwise arcs are drawn the same as Agg, and it isn't drawing sectors any more:
> Correct first point and orientation of Kiva QPainter arcs

- kiva/qpainter.py
Fall back to kiva.fonttools if Qt can't come up with a font name.  Fixes #972 
Benchmark looks like this on Python 3.8/PySide6/MacOS (appearance is likely to vary significantly based on OS and fonts installed):
Note that script and mono families are not rendered correctly due to #971 and #974.
> Render font families better in QPainter backend

- kiva/qpainter.py
- kiva/tests/drawing_tester.py
Also some changes to tests to make sure all weights are tested correctly.
Benchmark render on PySide6:
Fixes #989.
> Fix WEIGHT_EXTRAHEAVY on Qt6

- kiva/basecore2d.py
- kiva/tests/test_basecore2d.py
This:
- consistently uses Nx2 numpy arrays to store path points
- doesn't create a new subpath after a `LINES` function (so consecutive arc, curve, etc. commands add to the subpath).
A drive-by fix gives a default implementation for `show_text_at_point()`.
Image from the benchmark suite (for SVG):
Fixes #986.
> Fix the rendering of polygons in basecore2d-based backends

- kiva/basecore2d.py
- kiva/cairo.py
- kiva/celiagg.py
- kiva/pdf.py
- kiva/qpainter.py
- kiva/tests/drawing_tester.py
- kiva/tests/test_svg_drawing.py
This consists of:
- adding a simple implementation of `arc_to` for `basecore2d.GraphicsContext`
- removing the implementations of `arc_to` (which uses cubic beziers) and `quad_curve_to` (which raises masking the superclass) from the PDF backend. It inherits from `basecore2d.GraphicsContext` so we just use the implementations from that.
- adding tests for the curve methods to the drawing tester mixin.
Note that the PS and SVG backends won't draw eg. a rounded rectangle correctly until #987 is merged.
> Ensure all backends implement `arc_to` and `quad_curve_to`

- setup.py
This allows Twine to publish to PyPI without warning about long text content type.
> Add long description content type

- .github/workflows/bleeding-edge.yml
- .github/workflows/test-with-edm.yml
- ci/.edm.yaml
- ci/edmtool.py
- ci/requirements_3.6.txt
- ci/requirements_3.8.txt
- enable/__init__.py
- enable/savage/svg/tests/test_document.py
- pyproject.toml
This gets CI back into a working state by:
- restricting PyPDF to a version before 3.0 (this is used in testing only) - #1008 
- restricting pyglet to a version < 2 - #1010 
- mocking svg url requests
- turning off wx tests for linux (we can't get a compatible wheel for the new ubuntu) - #1009 tracks this for the future
Everything is passing: https://github.com/enthought/enable/actions/runs/4186677329
There is a warning about set-output, but I don't think it is us.
> Restore CI to working state

- .github/workflows/test-with-pip.yml
- enable/qt4/base_window.py
- enable/qt4/scrollbar.py
This was happening implicitly until https://bugs.python.org/issue36048 This makes it explicit, which means things should work with PyQt5 on Python 3.10.
Fixes #1037
> Add explicit float -> int conversion for Qt

- kiva/basecore2d.py
- kiva/line_state.py
- kiva/ps.py
- kiva/svg.py
- kiva/tests/test_quartz.py
- kiva/trait_defs/ui/wx/kiva_font_editor.py
Note that in some cases there are more modern idioms that might be used, ~but fixing those is for another PR~ looking at the actual code, it might be worth the effort to make them more idiomatic (eg. `is_dashed` should be much clearer as a one-liner).
> Replace uses of 0 and 1 with False and True, where appropriate.

- .github/workflows/bleeding-edge.yml
- .github/workflows/test-with-edm.yml
- .github/workflows/test-with-pip.yml
This ensures that we are getting a new framebuffer for each test.
Thanks to @mdickinson for the solution.
> Fix issues where xvfb-run was failing occasionally

- kiva/quartz/ABCGI.pyx
- kiva/tests/drawing_tester.py
Also adds a test for all backends which implement the method.
This was causing failures in Chaco scatterplots with the Quartz backend.
> Fix Quartz draw_path_at_points

- enable/qt/base_window.py
This PR:
- removes some remaining OpenGL code that is no longer used
- cleans up the logic around the creation of mouse events and drag events
This is a follow-up to some of the issues identified in #1030
> Clean-up of Enable Qt toolkit code

- kiva/basecore2d.py
- kiva/pdf.py
- kiva/qpainter.py
- kiva/quartz/ABCGI.pyx
- kiva/tests/drawing_tester.py
Test setting colors, and fixes based on tests.
This addresses some issues seen with the segment plot in Chaco.
> Test setting colors, and fixes based on tests.

- enable/__init__.py
- enable/tests/test_brush.py
- kiva/tests/test_celiagg_drawing.py
Tests should run with just the "test" dependencies.
Fixes #543
> Fix test dependencies

- enable/qt/image.py
- enable/qt/oldagg.py
- kiva/agg/tests/test_font_loading.py
- kiva/image.py
- kiva/oldagg.py
- kiva/tests/agg/test_image.py
- kiva/tests/test_agg_drawing.py
- kiva/tests/test_graphics_context.py
This is a simple PR that reverses the dependency of `kiva.image` and `kiva.oldagg`.  This is a prepatory PR for eventually replacing the old agg backend with celiagg.
Next step would be closer API compatibility between Oldagg and Celiagg (in particular, an `Image` class for `Celiagg`) together with optional use of Celiagg in place of Oldagg for experimentation.
> Move kiva.image to kiva.oldagg

- .github/workflows/bleeding-edge.yml
- .github/workflows/test-with-edm.yml
- .github/workflows/test-with-pip.yml
- ci/edmtool.py
- ci/requirements_3.11.txt
- ci/requirements_3.6.txt
- ci/requirements_3.8.txt
- kiva/_cython_speedups.pyx
- kiva/_marker_renderer.pyx
- kiva/agg/src/agg_typemaps.i
- kiva/agg/src/gtk1/agg_bmp.cpp
- kiva/agg/src/numeric.i
- kiva/agg/src/osx/plat_support.i
- kiva/agg/src/rect.i
- kiva/agg/src/rgba.i
- kiva/agg/src/rgba_array.i
- kiva/agg/src/x11/agg_bmp.cpp
- kiva/compatibility.py
- kiva/line_state.py
- kiva/quartz/ABCGI.pyx
- kiva/quartz/CoreGraphics.pxi
- pyproject.toml
- setup.py
- Update code to work with Cython 3
- Update code to work with recent swig
- Update code to be compatible with numpy 2.x
- Update edm testing to build on Python 3.11
- Update pip testing to build on Python 3.10 and 3.11
- Use latest github actions in github workflows
- Install missing dependencies for pip linux builds that build wxPython
- Update edmtool.py
- Support Python 3.11
- Remove support for Python < 3.11
- Use the  build package
- Install wxPython from EDS
> Fix build issues with enable
