dev_requirements.txt
This may or may not work. I'm just opening a PR to force Travis into action.
=> Force usage of Pyglet 1.1.4

enable/tests/tools/button_tool_test_case.py
This slipped in accidentally with #168
=> Replace multi-context with-statements with multiple with-statements

README.rst, enable/__init__.py, setup.py
This PR fixes issues similar to #179 and provides a more details on the build and runtime requirements
=> Fix enable setup

kiva/agg/src/affine_matrix.i, kiva/agg/src/constants.i, kiva/agg/src/hit_test.i, kiva/agg/src/rgba.i
Recent version of swig (3.0.5) broke the build of enable. This pull request fixes the issue. See https://github.com/swig/swig/issues/221#issuecomment-54469375
=> fixes for recent swig

kiva/agg/src/hit_test.i
The `.ndim` attribute is suggested instead.
=> BUG: numpy.rank() is deprecated.

enable/savage/svg/document.py, kiva/pdf.py, kiva/ps.py, kiva/quartz/ABCGI.pyx, kiva/svg.py
Remove a few deprecated PIL API calls via compat methods.
=> Pillow 3.0 fixes

enable/savage/svg/attributes.py, travis-ci-requirements
=> Make savage compatible with newer PyParsing versions.

enable/savage/compliance/comparator.py, enable/savage/compliance/viewer.py, enable/savage/svg/attributes.py, enable/savage/svg/css/colour.py, enable/savage/svg/document.py, enable/savage/svg/tests/test_document.py, enable/savage/trait_defs/ui/qt4/svg_editor.py, kiva/agg/src/affine_matrix.i, kiva/agg/src/gl/plat_support.i, kiva/agg/src/graphics_context.i, kiva/agg/src/numeric.i, kiva/agg/src/rgba.i, kiva/fonttools/fontTools/ttLib/__init__.py, kiva/fonttools/fontTools/ttLib/macUtils.py, kiva/fonttools/font_manager.py, kiva/pdfmetrics.py, kiva/ps.py, kiva/quartz/__init__.py, kiva/quartz/mac_context.c, kiva/quartz/setup.py, kiva/svg.py, setup.py
This PR makes the minimal changes necessary (plus some minor whitespace cleanup) to allow enable to build on Python 3 / OS X.
=> Fixes for Python 3 on OS X.

examples/kiva_explorer.py
Add a really simple traitsui view for playing with Kiva.
=> Kiva explorer demo

examples/kiva_explorer.py
=> Add an FPS display to the kiva explorer demo

CHANGES.txt, setup.py
Beginning the patch release...
=> Release 4.6.1

setup.py
PR for 4.6.2 release.
@jwiggins: do you have time to review / comment?
=> Make 4.6.2 release.

setup.py
=> FIX: Increment micro version number

ci/requirements.txt
This PR updates to the most recent release of fonttools, mainly to address the issue described in #306.
=> Update to the most recent release of fonttools. Closes #306.

kiva/_cython_speedups.cpp, kiva/_cython_speedups.pyx, kiva/tests/points_in_polygon_test.py
Fixes enthought/chaco#417
Fixes enthought/chaco#419
Fixes enthought/chaco#420
=> BUG: Ensure contiguity for memoryview arrays.

kiva/pdf.py
=> Don't clobber a passed-in font object

enable/tests/tools/hover_tool_test_case.py, enable/tools/hover_tool.py
Closes #324
I still need to write some tests for this tool, so that will take a few days at the least.
=> Use non-toolkit-specific Timer class

kiva/agg/src/agg_typemaps.i, kiva/agg/src/graphics_context.i, kiva/tests/test_agg_drawing.py
=> Fix TypeError when passing unicode args to agg gradient methods

CHANGES.txt, setup.py
Once this looks good, I'll tag the commit and unflip the release flag in `setup.py`.
=> Release 4.8.0

ci/edmtool.py, ci/requirements.txt, enable/__init__.py, setup.py
=> Add optional demo dependencies to setup.py

README.rst
* Update links to use HTTPS / new addresses
* Use SVG coverage badge for consistency
=> README: Update badge and links

kiva/fonttools/font_manager.py
This PR fixes a nitpicky change - a spelling mistake. I noticed this when I ran the testsuite. I noticed this when testing #448 locally
=> Nit-picky change, fix a spelling mistake

enable/qt4/base_window.py, enable/wx/base_window.py
fixes #313 
This PR simply adds warnings if attempted imports fail.
=> Warn if attempted imports fail

kiva/fonttools/tests/test_font_manager.py
I also reviewed and verified the changes in #405. This PR is targeting #405 to address @jwiggins's review comments.
=> [Targeting #405] Fix test printing to console and unused variable

kiva/agg/src/graphics_context.i
fixes #504 
This was missed when addressing #415
=> Remove use of six from graphics_context.i

.github/workflows/test-with-edm.yml, ci/edmtool.py
Another incremental step towards replicating all existing Travis/Appveyor jobs on GitHub Actions.
This PR adds a job to run tests against Linux.
=> Add Linux job to CI on GitHub Actions

enable/colors.py, enable/savage/trait_defs/ui/svg_button_editor.py, enable/savage/trait_defs/ui/svg_editor.py, enable/savage/trait_defs/ui/toolkit.py, enable/tests/primitives/test_image.py, enable/tests/qt4/test_scrollbar.py, enable/tests/test_component_editor.py, enable/tests/tools/pyface/test_commands.py, enable/tests/tools/pyface/test_move_command_tool.py, enable/tests/tools/pyface/test_resize_command_tool.py, enable/tests/tools/pyface/test_undo_tool.py, enable/tests/tools/test_button_tool.py, enable/toolkit.py, enable/trait_defs/ui/wx/rgba_color_editor.py
This PR updates the imports from ets package to import from their respective api modules instead of importing from their internals, where possible.
=> Use traits.api, traitsui.api and pyface.api where possible.

kiva/fonttools/font_manager.py
Closes #394
This PR removes `is_string_like`, because it's not needed. It was being used in two places: `FontProperties.__init__` and `FontProperties.set_family`. The usage in `FontProperties.__init__` was removed entirely, because it was guarding a call to `self.set_fontconfig_pattern` which, as far as I can tell, was never copied into the kiva code from matplotlib (see 1fe9c35c1f28e8b8e23c8a3614dc04e606227dc5. Just look at it.).
=> Remove is_string_like

setup.py
closes #435 
This PR updates setup.py so we can make release candidates
=> update setup.py to allow release candidates

setup.py
[targeting maint/5.0]
This PR simply sets `IS_RELEASED` to `True`, and `PRERELEASE` to "rc1" (and bumps version to the correct 5.0.0).
=> Release Candidate 5.0.0rc1

enable/colors.py, enable/component_editor.py, enable/tools/hover_tool.py, enable/trait_defs/rgba_color_trait.py, enable/trait_defs/ui/rgba_color_editor.py, kiva/quartz/__init__.py, kiva/trait_defs/kiva_font_trait.py
I'm guessing we don't want to use "Squash Merge" for this PR?
=> Cherrypick Qt fixes into 5.0 maintenance branch

enable/wx/base_window.py, enable/wx/cairo.py, enable/wx/gl.py, enable/wx/image.py, enable/wx/quartz.py, kiva/cairo.py
This is the Wx part of #591
Fixes #517
Fixes #412
=> Add HiDPI support for Wx

docs/source/conf.py, docs/source/enable_concepts.rst, docs/source/enable_constraints_layout.rst, docs/source/enable_toolkit_selection.rst, docs/source/index.rst, setup.py
This is the 5.0.0rc2 release. I've added #597 to the mix here, because documentation is always a welcome addition 😉.
=> Release 5.0.0rc2

CHANGES.txt
=> Update CHANGES.txt to include recent cherry-picks into 5.0.0

.github/workflows/bleeding-edge.yml
Cron job is failing: https://github.com/enthought/enable/actions/runs/579901110
Adding Cython and SWIG to the environment _should_ fix the problem
=> Add Cython and SWIG to cron job build deps

ci/edmtool.py, setup.py
=> Release 5.0.0

enable/base_tool.py, enable/tests/test_key_spec.py
=> Fix KeySpec.from_string

enable/abstract_window.py, enable/base_tool.py, enable/tests/test_component_editor.py, enable/tests/test_key_spec.py
We'll be releasing a 5.0.1 version in the not-too-distant future. Included in that should be the fixes from #635 and #638.
=> Cherry pick fixes into the maint/5.0 branch

docs/source/index.rst, docs/source/kiva/font_manager.rst
@rahulporuri You asked about this the other day, so I decided to write down what I know before I forget.
=> Add some developer docs for Kiva's FontManager

setup.py
=> Release Candidate 5.1.0rc1

CHANGES.txt
Part of #719
This contains all the changes between 5.0.1 and now. More will be added as they are merged, but maybe not in this PR.
=> 5.1.0 Changelog edits

enable/__init__.py
=> Require a minimum of Traits 6.2.0

setup.py
One more and then we probably do the real 5.1.0.
I've already added the tag for this prerelease.
=> Release 5.1.0rc2

kiva/fonttools/_database.py, kiva/fonttools/_scan_parse.py, kiva/fonttools/_util.py, kiva/fonttools/tests/test_scan_parse.py
=> Add support for determining the language of a font

setup.py
=> 5.1.0 Release

setup.py
The merge commit from this PR will be tagged as the 5.2.0 release candidate
=> Enable Release Candidate 5.2.0rc1

MANIFEST.in
=> Include pyproject.toml in manifset

MANIFEST.in, enable/__init__.py
This PR pulls 2 PRs that were made on the `maint/5.2` maintenance brach up into master.
=> Pull PRs from maint/5.2 back into master

setup.py
The merge commit from this PR will be tagged as the 5.2.0 release
=> Enable Release 5.2.0

.github/workflows/bleeding-edge.yml, .github/workflows/test-with-edm.yml
This PR sets up slack notification for cron job in this repository. I manually triggered the cron job on this branch to check that the slack notification gets fired as expected. Ref https://github.com/enthought/enable/actions/runs/1027365281.
The last step in https://github.com/enthought/ets/issues/65.
Note : I apologize for the noise in the commit history. I'll make sure to remove the unnecesasry commit messages when i finally squash-merge this PR, once it's green and approved.
=> Setup slack notification on cron jobs

setup.py
The merge commit from this PR will be tagged as the 5.2.1 bugfix release
=> Enable Release 5.2.1

enable/qt4/base_window.py, enable/qt4/constants.py
=> Replace QMidButton with QMiddleButton.

CHANGES.txt
Straightforward update of the changelog in preparation for 5.3.0 release.
=> Update the changelog

setup.py
=> Release 5.3.0

setup.py
=> Post-release version bump

setup.py
Do a micro-bump for 5.3.x maintenance branch.
=> Post release version bump for 5.3.x maintenance

enable/gcbench/suite.py
Currently there is almost no agreement over what behaviour should be in a number of backends.
This PR adds some benchmarks to the suite to explore:
- arc drawing
- font selection
=> More Benchmarks

CHANGES.txt
=> Update changelog for 5.3.1 release

setup.py
Enable 5.3.1 release version commit.
=> Release 5.3.1

setup.py
=> 5.3.1 post-release version-bump

kiva/agg/tests/test_affine_matrix.py, kiva/agg/tests/test_utils.py, kiva/basecore2d.py, kiva/line_state.py, kiva/tests/agg/test_image.py, kiva/tests/test_affine.py, kiva/tests/test_basecore2d.py, kiva/tests/test_graphics_context.py
Change all the numpy.alltrue to numpy.all
Fixes https://github.com/enthought/enable/issues/991
This replaces issue #1013 , updated from the latest main branch
=> replace all true

CHANGES.txt, setup.py
=> Release 6.0.0

enable/__init__.py, pyproject.toml
Hopefully this is a quick-fix for #1060 - but a more permanent fix will be needed at some future point.
Now includes a work-around for #1062 (hopefully)
=> Insist on Cython prior to 3.0
